/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.models.V1alpha1AnalysisTemplateSpecDryRun;
import io.argoproj.models.V1alpha1AnalysisTemplateSpecMeasurementRetention;
import io.argoproj.models.V1alpha1AnalysisTemplateSpecProviderJobMetadata;
import io.argoproj.models.V1alpha1RolloutSpecStrategyBlueGreenPostPromotionAnalysisArgs;
import io.argoproj.models.V1alpha1RolloutSpecStrategyBlueGreenPostPromotionAnalysisTemplates;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha1RolloutSpecStrategyCanaryAnalysis
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-19T02:24:32.086Z[Etc/UTC]")
public class V1alpha1RolloutSpecStrategyCanaryAnalysis {
  public static final String SERIALIZED_NAME_ANALYSIS_RUN_METADATA = "analysisRunMetadata";
  @SerializedName(SERIALIZED_NAME_ANALYSIS_RUN_METADATA)
  private V1alpha1AnalysisTemplateSpecProviderJobMetadata analysisRunMetadata;

  public static final String SERIALIZED_NAME_ARGS = "args";
  @SerializedName(SERIALIZED_NAME_ARGS)
  private List<V1alpha1RolloutSpecStrategyBlueGreenPostPromotionAnalysisArgs> args = null;

  public static final String SERIALIZED_NAME_DRY_RUN = "dryRun";
  @SerializedName(SERIALIZED_NAME_DRY_RUN)
  private List<V1alpha1AnalysisTemplateSpecDryRun> dryRun = null;

  public static final String SERIALIZED_NAME_MEASUREMENT_RETENTION = "measurementRetention";
  @SerializedName(SERIALIZED_NAME_MEASUREMENT_RETENTION)
  private List<V1alpha1AnalysisTemplateSpecMeasurementRetention> measurementRetention = null;

  public static final String SERIALIZED_NAME_STARTING_STEP = "startingStep";
  @SerializedName(SERIALIZED_NAME_STARTING_STEP)
  private Integer startingStep;

  public static final String SERIALIZED_NAME_TEMPLATES = "templates";
  @SerializedName(SERIALIZED_NAME_TEMPLATES)
  private List<V1alpha1RolloutSpecStrategyBlueGreenPostPromotionAnalysisTemplates> templates = null;


  public V1alpha1RolloutSpecStrategyCanaryAnalysis analysisRunMetadata(V1alpha1AnalysisTemplateSpecProviderJobMetadata analysisRunMetadata) {
    
    this.analysisRunMetadata = analysisRunMetadata;
    return this;
  }

   /**
   * Get analysisRunMetadata
   * @return analysisRunMetadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1AnalysisTemplateSpecProviderJobMetadata getAnalysisRunMetadata() {
    return analysisRunMetadata;
  }


  public void setAnalysisRunMetadata(V1alpha1AnalysisTemplateSpecProviderJobMetadata analysisRunMetadata) {
    this.analysisRunMetadata = analysisRunMetadata;
  }


  public V1alpha1RolloutSpecStrategyCanaryAnalysis args(List<V1alpha1RolloutSpecStrategyBlueGreenPostPromotionAnalysisArgs> args) {
    
    this.args = args;
    return this;
  }

  public V1alpha1RolloutSpecStrategyCanaryAnalysis addArgsItem(V1alpha1RolloutSpecStrategyBlueGreenPostPromotionAnalysisArgs argsItem) {
    if (this.args == null) {
      this.args = new ArrayList<>();
    }
    this.args.add(argsItem);
    return this;
  }

   /**
   * Get args
   * @return args
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1RolloutSpecStrategyBlueGreenPostPromotionAnalysisArgs> getArgs() {
    return args;
  }


  public void setArgs(List<V1alpha1RolloutSpecStrategyBlueGreenPostPromotionAnalysisArgs> args) {
    this.args = args;
  }


  public V1alpha1RolloutSpecStrategyCanaryAnalysis dryRun(List<V1alpha1AnalysisTemplateSpecDryRun> dryRun) {
    
    this.dryRun = dryRun;
    return this;
  }

  public V1alpha1RolloutSpecStrategyCanaryAnalysis addDryRunItem(V1alpha1AnalysisTemplateSpecDryRun dryRunItem) {
    if (this.dryRun == null) {
      this.dryRun = new ArrayList<>();
    }
    this.dryRun.add(dryRunItem);
    return this;
  }

   /**
   * Get dryRun
   * @return dryRun
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1AnalysisTemplateSpecDryRun> getDryRun() {
    return dryRun;
  }


  public void setDryRun(List<V1alpha1AnalysisTemplateSpecDryRun> dryRun) {
    this.dryRun = dryRun;
  }


  public V1alpha1RolloutSpecStrategyCanaryAnalysis measurementRetention(List<V1alpha1AnalysisTemplateSpecMeasurementRetention> measurementRetention) {
    
    this.measurementRetention = measurementRetention;
    return this;
  }

  public V1alpha1RolloutSpecStrategyCanaryAnalysis addMeasurementRetentionItem(V1alpha1AnalysisTemplateSpecMeasurementRetention measurementRetentionItem) {
    if (this.measurementRetention == null) {
      this.measurementRetention = new ArrayList<>();
    }
    this.measurementRetention.add(measurementRetentionItem);
    return this;
  }

   /**
   * Get measurementRetention
   * @return measurementRetention
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1AnalysisTemplateSpecMeasurementRetention> getMeasurementRetention() {
    return measurementRetention;
  }


  public void setMeasurementRetention(List<V1alpha1AnalysisTemplateSpecMeasurementRetention> measurementRetention) {
    this.measurementRetention = measurementRetention;
  }


  public V1alpha1RolloutSpecStrategyCanaryAnalysis startingStep(Integer startingStep) {
    
    this.startingStep = startingStep;
    return this;
  }

   /**
   * Get startingStep
   * @return startingStep
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getStartingStep() {
    return startingStep;
  }


  public void setStartingStep(Integer startingStep) {
    this.startingStep = startingStep;
  }


  public V1alpha1RolloutSpecStrategyCanaryAnalysis templates(List<V1alpha1RolloutSpecStrategyBlueGreenPostPromotionAnalysisTemplates> templates) {
    
    this.templates = templates;
    return this;
  }

  public V1alpha1RolloutSpecStrategyCanaryAnalysis addTemplatesItem(V1alpha1RolloutSpecStrategyBlueGreenPostPromotionAnalysisTemplates templatesItem) {
    if (this.templates == null) {
      this.templates = new ArrayList<>();
    }
    this.templates.add(templatesItem);
    return this;
  }

   /**
   * Get templates
   * @return templates
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1RolloutSpecStrategyBlueGreenPostPromotionAnalysisTemplates> getTemplates() {
    return templates;
  }


  public void setTemplates(List<V1alpha1RolloutSpecStrategyBlueGreenPostPromotionAnalysisTemplates> templates) {
    this.templates = templates;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1RolloutSpecStrategyCanaryAnalysis v1alpha1RolloutSpecStrategyCanaryAnalysis = (V1alpha1RolloutSpecStrategyCanaryAnalysis) o;
    return Objects.equals(this.analysisRunMetadata, v1alpha1RolloutSpecStrategyCanaryAnalysis.analysisRunMetadata) &&
        Objects.equals(this.args, v1alpha1RolloutSpecStrategyCanaryAnalysis.args) &&
        Objects.equals(this.dryRun, v1alpha1RolloutSpecStrategyCanaryAnalysis.dryRun) &&
        Objects.equals(this.measurementRetention, v1alpha1RolloutSpecStrategyCanaryAnalysis.measurementRetention) &&
        Objects.equals(this.startingStep, v1alpha1RolloutSpecStrategyCanaryAnalysis.startingStep) &&
        Objects.equals(this.templates, v1alpha1RolloutSpecStrategyCanaryAnalysis.templates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(analysisRunMetadata, args, dryRun, measurementRetention, startingStep, templates);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1RolloutSpecStrategyCanaryAnalysis {\n");
    sb.append("    analysisRunMetadata: ").append(toIndentedString(analysisRunMetadata)).append("\n");
    sb.append("    args: ").append(toIndentedString(args)).append("\n");
    sb.append("    dryRun: ").append(toIndentedString(dryRun)).append("\n");
    sb.append("    measurementRetention: ").append(toIndentedString(measurementRetention)).append("\n");
    sb.append("    startingStep: ").append(toIndentedString(startingStep)).append("\n");
    sb.append("    templates: ").append(toIndentedString(templates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

