/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.models.V1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMeshVirtualNodeGroup;
import io.argoproj.models.V1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMeshVirtualService;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMesh
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-19T02:24:32.086Z[Etc/UTC]")
public class V1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMesh {
  public static final String SERIALIZED_NAME_VIRTUAL_NODE_GROUP = "virtualNodeGroup";
  @SerializedName(SERIALIZED_NAME_VIRTUAL_NODE_GROUP)
  private V1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMeshVirtualNodeGroup virtualNodeGroup;

  public static final String SERIALIZED_NAME_VIRTUAL_SERVICE = "virtualService";
  @SerializedName(SERIALIZED_NAME_VIRTUAL_SERVICE)
  private V1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMeshVirtualService virtualService;


  public V1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMesh virtualNodeGroup(V1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMeshVirtualNodeGroup virtualNodeGroup) {
    
    this.virtualNodeGroup = virtualNodeGroup;
    return this;
  }

   /**
   * Get virtualNodeGroup
   * @return virtualNodeGroup
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMeshVirtualNodeGroup getVirtualNodeGroup() {
    return virtualNodeGroup;
  }


  public void setVirtualNodeGroup(V1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMeshVirtualNodeGroup virtualNodeGroup) {
    this.virtualNodeGroup = virtualNodeGroup;
  }


  public V1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMesh virtualService(V1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMeshVirtualService virtualService) {
    
    this.virtualService = virtualService;
    return this;
  }

   /**
   * Get virtualService
   * @return virtualService
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMeshVirtualService getVirtualService() {
    return virtualService;
  }


  public void setVirtualService(V1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMeshVirtualService virtualService) {
    this.virtualService = virtualService;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMesh v1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMesh = (V1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMesh) o;
    return Objects.equals(this.virtualNodeGroup, v1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMesh.virtualNodeGroup) &&
        Objects.equals(this.virtualService, v1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMesh.virtualService);
  }

  @Override
  public int hashCode() {
    return Objects.hash(virtualNodeGroup, virtualService);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMesh {\n");
    sb.append("    virtualNodeGroup: ").append(toIndentedString(virtualNodeGroup)).append("\n");
    sb.append("    virtualService: ").append(toIndentedString(virtualService)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

