/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioDestinationRule
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-19T02:24:32.086Z[Etc/UTC]")
public class V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioDestinationRule {
  public static final String SERIALIZED_NAME_CANARY_SUBSET_NAME = "canarySubsetName";
  @SerializedName(SERIALIZED_NAME_CANARY_SUBSET_NAME)
  private String canarySubsetName;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_STABLE_SUBSET_NAME = "stableSubsetName";
  @SerializedName(SERIALIZED_NAME_STABLE_SUBSET_NAME)
  private String stableSubsetName;


  public V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioDestinationRule canarySubsetName(String canarySubsetName) {
    
    this.canarySubsetName = canarySubsetName;
    return this;
  }

   /**
   * Get canarySubsetName
   * @return canarySubsetName
  **/
  @ApiModelProperty(required = true, value = "")

  public String getCanarySubsetName() {
    return canarySubsetName;
  }


  public void setCanarySubsetName(String canarySubsetName) {
    this.canarySubsetName = canarySubsetName;
  }


  public V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioDestinationRule name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioDestinationRule stableSubsetName(String stableSubsetName) {
    
    this.stableSubsetName = stableSubsetName;
    return this;
  }

   /**
   * Get stableSubsetName
   * @return stableSubsetName
  **/
  @ApiModelProperty(required = true, value = "")

  public String getStableSubsetName() {
    return stableSubsetName;
  }


  public void setStableSubsetName(String stableSubsetName) {
    this.stableSubsetName = stableSubsetName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioDestinationRule v1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioDestinationRule = (V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioDestinationRule) o;
    return Objects.equals(this.canarySubsetName, v1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioDestinationRule.canarySubsetName) &&
        Objects.equals(this.name, v1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioDestinationRule.name) &&
        Objects.equals(this.stableSubsetName, v1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioDestinationRule.stableSubsetName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(canarySubsetName, name, stableSubsetName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioDestinationRule {\n");
    sb.append("    canarySubsetName: ").append(toIndentedString(canarySubsetName)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    stableSubsetName: ").append(toIndentedString(stableSubsetName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

