/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.models.V1alpha1FieldRef;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ArgumentValueFrom defines references to fields within resources to grab for the value (i.e. Pod Template Hash)
 */
@ApiModel(description = "ArgumentValueFrom defines references to fields within resources to grab for the value (i.e. Pod Template Hash)")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-19T21:57:47.017Z[Etc/UTC]")
public class V1alpha1ArgumentValueFrom {
  public static final String SERIALIZED_NAME_FIELD_REF = "fieldRef";
  @SerializedName(SERIALIZED_NAME_FIELD_REF)
  private V1alpha1FieldRef fieldRef;

  public static final String SERIALIZED_NAME_POD_TEMPLATE_HASH_VALUE = "podTemplateHashValue";
  @SerializedName(SERIALIZED_NAME_POD_TEMPLATE_HASH_VALUE)
  private String podTemplateHashValue;


  public V1alpha1ArgumentValueFrom fieldRef(V1alpha1FieldRef fieldRef) {
    
    this.fieldRef = fieldRef;
    return this;
  }

   /**
   * Get fieldRef
   * @return fieldRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FieldRef getFieldRef() {
    return fieldRef;
  }


  public void setFieldRef(V1alpha1FieldRef fieldRef) {
    this.fieldRef = fieldRef;
  }


  public V1alpha1ArgumentValueFrom podTemplateHashValue(String podTemplateHashValue) {
    
    this.podTemplateHashValue = podTemplateHashValue;
    return this;
  }

   /**
   * PodTemplateHashValue gets the value from one of the children ReplicaSet&#39;s Pod Template Hash
   * @return podTemplateHashValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "PodTemplateHashValue gets the value from one of the children ReplicaSet's Pod Template Hash")

  public String getPodTemplateHashValue() {
    return podTemplateHashValue;
  }


  public void setPodTemplateHashValue(String podTemplateHashValue) {
    this.podTemplateHashValue = podTemplateHashValue;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1ArgumentValueFrom v1alpha1ArgumentValueFrom = (V1alpha1ArgumentValueFrom) o;
    return Objects.equals(this.fieldRef, v1alpha1ArgumentValueFrom.fieldRef) &&
        Objects.equals(this.podTemplateHashValue, v1alpha1ArgumentValueFrom.podTemplateHashValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fieldRef, podTemplateHashValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1ArgumentValueFrom {\n");
    sb.append("    fieldRef: ").append(toIndentedString(fieldRef)).append("\n");
    sb.append("    podTemplateHashValue: ").append(toIndentedString(podTemplateHashValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

