/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.models.V1alpha1Argument;
import io.argoproj.models.V1alpha1DryRun;
import io.argoproj.models.V1alpha1MeasurementRetention;
import io.argoproj.models.V1alpha1Metric;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * AnalysisTemplateSpec is the specification for a AnalysisTemplate resource
 */
@ApiModel(description = "AnalysisTemplateSpec is the specification for a AnalysisTemplate resource")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-19T21:57:47.017Z[Etc/UTC]")
public class V1alpha1AnalysisTemplateSpec {
  public static final String SERIALIZED_NAME_ARGS = "args";
  @SerializedName(SERIALIZED_NAME_ARGS)
  private List<V1alpha1Argument> args = null;

  public static final String SERIALIZED_NAME_DRY_RUN = "dryRun";
  @SerializedName(SERIALIZED_NAME_DRY_RUN)
  private List<V1alpha1DryRun> dryRun = null;

  public static final String SERIALIZED_NAME_MEASUREMENT_RETENTION = "measurementRetention";
  @SerializedName(SERIALIZED_NAME_MEASUREMENT_RETENTION)
  private List<V1alpha1MeasurementRetention> measurementRetention = null;

  public static final String SERIALIZED_NAME_METRICS = "metrics";
  @SerializedName(SERIALIZED_NAME_METRICS)
  private List<V1alpha1Metric> metrics = new ArrayList<>();


  public V1alpha1AnalysisTemplateSpec args(List<V1alpha1Argument> args) {
    
    this.args = args;
    return this;
  }

  public V1alpha1AnalysisTemplateSpec addArgsItem(V1alpha1Argument argsItem) {
    if (this.args == null) {
      this.args = new ArrayList<>();
    }
    this.args.add(argsItem);
    return this;
  }

   /**
   * Args are the list of arguments to the template
   * @return args
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Args are the list of arguments to the template")

  public List<V1alpha1Argument> getArgs() {
    return args;
  }


  public void setArgs(List<V1alpha1Argument> args) {
    this.args = args;
  }


  public V1alpha1AnalysisTemplateSpec dryRun(List<V1alpha1DryRun> dryRun) {
    
    this.dryRun = dryRun;
    return this;
  }

  public V1alpha1AnalysisTemplateSpec addDryRunItem(V1alpha1DryRun dryRunItem) {
    if (this.dryRun == null) {
      this.dryRun = new ArrayList<>();
    }
    this.dryRun.add(dryRunItem);
    return this;
  }

   /**
   * DryRun object contains the settings for running the analysis in Dry-Run mode
   * @return dryRun
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "DryRun object contains the settings for running the analysis in Dry-Run mode")

  public List<V1alpha1DryRun> getDryRun() {
    return dryRun;
  }


  public void setDryRun(List<V1alpha1DryRun> dryRun) {
    this.dryRun = dryRun;
  }


  public V1alpha1AnalysisTemplateSpec measurementRetention(List<V1alpha1MeasurementRetention> measurementRetention) {
    
    this.measurementRetention = measurementRetention;
    return this;
  }

  public V1alpha1AnalysisTemplateSpec addMeasurementRetentionItem(V1alpha1MeasurementRetention measurementRetentionItem) {
    if (this.measurementRetention == null) {
      this.measurementRetention = new ArrayList<>();
    }
    this.measurementRetention.add(measurementRetentionItem);
    return this;
  }

   /**
   * MeasurementRetention object contains the settings for retaining the number of measurements during the analysis
   * @return measurementRetention
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "MeasurementRetention object contains the settings for retaining the number of measurements during the analysis")

  public List<V1alpha1MeasurementRetention> getMeasurementRetention() {
    return measurementRetention;
  }


  public void setMeasurementRetention(List<V1alpha1MeasurementRetention> measurementRetention) {
    this.measurementRetention = measurementRetention;
  }


  public V1alpha1AnalysisTemplateSpec metrics(List<V1alpha1Metric> metrics) {
    
    this.metrics = metrics;
    return this;
  }

  public V1alpha1AnalysisTemplateSpec addMetricsItem(V1alpha1Metric metricsItem) {
    this.metrics.add(metricsItem);
    return this;
  }

   /**
   * Metrics contains the list of metrics to query as part of an analysis run
   * @return metrics
  **/
  @ApiModelProperty(required = true, value = "Metrics contains the list of metrics to query as part of an analysis run")

  public List<V1alpha1Metric> getMetrics() {
    return metrics;
  }


  public void setMetrics(List<V1alpha1Metric> metrics) {
    this.metrics = metrics;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1AnalysisTemplateSpec v1alpha1AnalysisTemplateSpec = (V1alpha1AnalysisTemplateSpec) o;
    return Objects.equals(this.args, v1alpha1AnalysisTemplateSpec.args) &&
        Objects.equals(this.dryRun, v1alpha1AnalysisTemplateSpec.dryRun) &&
        Objects.equals(this.measurementRetention, v1alpha1AnalysisTemplateSpec.measurementRetention) &&
        Objects.equals(this.metrics, v1alpha1AnalysisTemplateSpec.metrics);
  }

  @Override
  public int hashCode() {
    return Objects.hash(args, dryRun, measurementRetention, metrics);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1AnalysisTemplateSpec {\n");
    sb.append("    args: ").append(toIndentedString(args)).append("\n");
    sb.append("    dryRun: ").append(toIndentedString(dryRun)).append("\n");
    sb.append("    measurementRetention: ").append(toIndentedString(measurementRetention)).append("\n");
    sb.append("    metrics: ").append(toIndentedString(metrics)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

