/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMeshVirtualService
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-19T02:24:32.086Z[Etc/UTC]")
public class V1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMeshVirtualService {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_ROUTES = "routes";
  @SerializedName(SERIALIZED_NAME_ROUTES)
  private List<String> routes = null;


  public V1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMeshVirtualService name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMeshVirtualService routes(List<String> routes) {
    
    this.routes = routes;
    return this;
  }

  public V1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMeshVirtualService addRoutesItem(String routesItem) {
    if (this.routes == null) {
      this.routes = new ArrayList<>();
    }
    this.routes.add(routesItem);
    return this;
  }

   /**
   * Get routes
   * @return routes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getRoutes() {
    return routes;
  }


  public void setRoutes(List<String> routes) {
    this.routes = routes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMeshVirtualService v1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMeshVirtualService = (V1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMeshVirtualService) o;
    return Objects.equals(this.name, v1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMeshVirtualService.name) &&
        Objects.equals(this.routes, v1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMeshVirtualService.routes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, routes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1RolloutSpecStrategyCanaryTrafficRoutingAppMeshVirtualService {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    routes: ").append(toIndentedString(routes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

