/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PrometheusMetric defines the prometheus query to perform canary analysis
 */
@ApiModel(description = "PrometheusMetric defines the prometheus query to perform canary analysis")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-19T21:57:47.017Z[Etc/UTC]")
public class V1alpha1PrometheusMetric {
  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private String address;

  public static final String SERIALIZED_NAME_QUERY = "query";
  @SerializedName(SERIALIZED_NAME_QUERY)
  private String query;


  public V1alpha1PrometheusMetric address(String address) {
    
    this.address = address;
    return this;
  }

   /**
   * Address is the HTTP address and port of the prometheus server
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Address is the HTTP address and port of the prometheus server")

  public String getAddress() {
    return address;
  }


  public void setAddress(String address) {
    this.address = address;
  }


  public V1alpha1PrometheusMetric query(String query) {
    
    this.query = query;
    return this;
  }

   /**
   * Query is a raw prometheus query to perform
   * @return query
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Query is a raw prometheus query to perform")

  public String getQuery() {
    return query;
  }


  public void setQuery(String query) {
    this.query = query;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1PrometheusMetric v1alpha1PrometheusMetric = (V1alpha1PrometheusMetric) o;
    return Objects.equals(this.address, v1alpha1PrometheusMetric.address) &&
        Objects.equals(this.query, v1alpha1PrometheusMetric.query);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, query);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1PrometheusMetric {\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

