/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.models.V1alpha1AnalysisTemplateSpecProviderPrometheusAuthentication;
import io.argoproj.models.V1alpha1AnalysisTemplateSpecProviderPrometheusHeaders;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha1AnalysisTemplateSpecProviderPrometheus
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-19T02:24:32.086Z[Etc/UTC]")
public class V1alpha1AnalysisTemplateSpecProviderPrometheus {
  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private String address;

  public static final String SERIALIZED_NAME_AUTHENTICATION = "authentication";
  @SerializedName(SERIALIZED_NAME_AUTHENTICATION)
  private V1alpha1AnalysisTemplateSpecProviderPrometheusAuthentication authentication;

  public static final String SERIALIZED_NAME_HEADERS = "headers";
  @SerializedName(SERIALIZED_NAME_HEADERS)
  private List<V1alpha1AnalysisTemplateSpecProviderPrometheusHeaders> headers = null;

  public static final String SERIALIZED_NAME_INSECURE = "insecure";
  @SerializedName(SERIALIZED_NAME_INSECURE)
  private Boolean insecure;

  public static final String SERIALIZED_NAME_QUERY = "query";
  @SerializedName(SERIALIZED_NAME_QUERY)
  private String query;

  public static final String SERIALIZED_NAME_TIMEOUT = "timeout";
  @SerializedName(SERIALIZED_NAME_TIMEOUT)
  private Long timeout;


  public V1alpha1AnalysisTemplateSpecProviderPrometheus address(String address) {
    
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAddress() {
    return address;
  }


  public void setAddress(String address) {
    this.address = address;
  }


  public V1alpha1AnalysisTemplateSpecProviderPrometheus authentication(V1alpha1AnalysisTemplateSpecProviderPrometheusAuthentication authentication) {
    
    this.authentication = authentication;
    return this;
  }

   /**
   * Get authentication
   * @return authentication
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1AnalysisTemplateSpecProviderPrometheusAuthentication getAuthentication() {
    return authentication;
  }


  public void setAuthentication(V1alpha1AnalysisTemplateSpecProviderPrometheusAuthentication authentication) {
    this.authentication = authentication;
  }


  public V1alpha1AnalysisTemplateSpecProviderPrometheus headers(List<V1alpha1AnalysisTemplateSpecProviderPrometheusHeaders> headers) {
    
    this.headers = headers;
    return this;
  }

  public V1alpha1AnalysisTemplateSpecProviderPrometheus addHeadersItem(V1alpha1AnalysisTemplateSpecProviderPrometheusHeaders headersItem) {
    if (this.headers == null) {
      this.headers = new ArrayList<>();
    }
    this.headers.add(headersItem);
    return this;
  }

   /**
   * Get headers
   * @return headers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1AnalysisTemplateSpecProviderPrometheusHeaders> getHeaders() {
    return headers;
  }


  public void setHeaders(List<V1alpha1AnalysisTemplateSpecProviderPrometheusHeaders> headers) {
    this.headers = headers;
  }


  public V1alpha1AnalysisTemplateSpecProviderPrometheus insecure(Boolean insecure) {
    
    this.insecure = insecure;
    return this;
  }

   /**
   * Get insecure
   * @return insecure
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getInsecure() {
    return insecure;
  }


  public void setInsecure(Boolean insecure) {
    this.insecure = insecure;
  }


  public V1alpha1AnalysisTemplateSpecProviderPrometheus query(String query) {
    
    this.query = query;
    return this;
  }

   /**
   * Get query
   * @return query
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getQuery() {
    return query;
  }


  public void setQuery(String query) {
    this.query = query;
  }


  public V1alpha1AnalysisTemplateSpecProviderPrometheus timeout(Long timeout) {
    
    this.timeout = timeout;
    return this;
  }

   /**
   * Get timeout
   * @return timeout
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getTimeout() {
    return timeout;
  }


  public void setTimeout(Long timeout) {
    this.timeout = timeout;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1AnalysisTemplateSpecProviderPrometheus v1alpha1AnalysisTemplateSpecProviderPrometheus = (V1alpha1AnalysisTemplateSpecProviderPrometheus) o;
    return Objects.equals(this.address, v1alpha1AnalysisTemplateSpecProviderPrometheus.address) &&
        Objects.equals(this.authentication, v1alpha1AnalysisTemplateSpecProviderPrometheus.authentication) &&
        Objects.equals(this.headers, v1alpha1AnalysisTemplateSpecProviderPrometheus.headers) &&
        Objects.equals(this.insecure, v1alpha1AnalysisTemplateSpecProviderPrometheus.insecure) &&
        Objects.equals(this.query, v1alpha1AnalysisTemplateSpecProviderPrometheus.query) &&
        Objects.equals(this.timeout, v1alpha1AnalysisTemplateSpecProviderPrometheus.timeout);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, authentication, headers, insecure, query, timeout);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1AnalysisTemplateSpecProviderPrometheus {\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    authentication: ").append(toIndentedString(authentication)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    insecure: ").append(toIndentedString(insecure)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    timeout: ").append(toIndentedString(timeout)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

