/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * MeasurementRetention defines the settings for retaining the number of measurements during the analysis.
 */
@ApiModel(description = "MeasurementRetention defines the settings for retaining the number of measurements during the analysis.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-19T21:57:47.017Z[Etc/UTC]")
public class V1alpha1MeasurementRetention {
  public static final String SERIALIZED_NAME_LIMIT = "limit";
  @SerializedName(SERIALIZED_NAME_LIMIT)
  private Integer limit = 0;

  public static final String SERIALIZED_NAME_METRIC_NAME = "metricName";
  @SerializedName(SERIALIZED_NAME_METRIC_NAME)
  private String metricName = "";


  public V1alpha1MeasurementRetention limit(Integer limit) {
    
    this.limit = limit;
    return this;
  }

   /**
   * Limit is the maximum number of measurements to be retained for this given metric.
   * @return limit
  **/
  @ApiModelProperty(required = true, value = "Limit is the maximum number of measurements to be retained for this given metric.")

  public Integer getLimit() {
    return limit;
  }


  public void setLimit(Integer limit) {
    this.limit = limit;
  }


  public V1alpha1MeasurementRetention metricName(String metricName) {
    
    this.metricName = metricName;
    return this;
  }

   /**
   * MetricName is the name of the metric on which this retention policy should be applied.
   * @return metricName
  **/
  @ApiModelProperty(required = true, value = "MetricName is the name of the metric on which this retention policy should be applied.")

  public String getMetricName() {
    return metricName;
  }


  public void setMetricName(String metricName) {
    this.metricName = metricName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1MeasurementRetention v1alpha1MeasurementRetention = (V1alpha1MeasurementRetention) o;
    return Objects.equals(this.limit, v1alpha1MeasurementRetention.limit) &&
        Objects.equals(this.metricName, v1alpha1MeasurementRetention.metricName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(limit, metricName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1MeasurementRetention {\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    metricName: ").append(toIndentedString(metricName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

