/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha1StickinessConfig
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-19T21:57:47.017Z[Etc/UTC]")
public class V1alpha1StickinessConfig {
  public static final String SERIALIZED_NAME_DURATION_SECONDS = "durationSeconds";
  @SerializedName(SERIALIZED_NAME_DURATION_SECONDS)
  private Long durationSeconds = 0l;

  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  private Boolean enabled = false;


  public V1alpha1StickinessConfig durationSeconds(Long durationSeconds) {
    
    this.durationSeconds = durationSeconds;
    return this;
  }

   /**
   * Get durationSeconds
   * @return durationSeconds
  **/
  @ApiModelProperty(required = true, value = "")

  public Long getDurationSeconds() {
    return durationSeconds;
  }


  public void setDurationSeconds(Long durationSeconds) {
    this.durationSeconds = durationSeconds;
  }


  public V1alpha1StickinessConfig enabled(Boolean enabled) {
    
    this.enabled = enabled;
    return this;
  }

   /**
   * Get enabled
   * @return enabled
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getEnabled() {
    return enabled;
  }


  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1StickinessConfig v1alpha1StickinessConfig = (V1alpha1StickinessConfig) o;
    return Objects.equals(this.durationSeconds, v1alpha1StickinessConfig.durationSeconds) &&
        Objects.equals(this.enabled, v1alpha1StickinessConfig.enabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(durationSeconds, enabled);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1StickinessConfig {\n");
    sb.append("    durationSeconds: ").append(toIndentedString(durationSeconds)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

