/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.models.V1alpha1AnalysisTemplateSpecProviderJobSpecPodFailurePolicyRules;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha1AnalysisTemplateSpecProviderJobSpecPodFailurePolicy
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-19T02:24:32.086Z[Etc/UTC]")
public class V1alpha1AnalysisTemplateSpecProviderJobSpecPodFailurePolicy {
  public static final String SERIALIZED_NAME_RULES = "rules";
  @SerializedName(SERIALIZED_NAME_RULES)
  private List<V1alpha1AnalysisTemplateSpecProviderJobSpecPodFailurePolicyRules> rules = new ArrayList<>();


  public V1alpha1AnalysisTemplateSpecProviderJobSpecPodFailurePolicy rules(List<V1alpha1AnalysisTemplateSpecProviderJobSpecPodFailurePolicyRules> rules) {
    
    this.rules = rules;
    return this;
  }

  public V1alpha1AnalysisTemplateSpecProviderJobSpecPodFailurePolicy addRulesItem(V1alpha1AnalysisTemplateSpecProviderJobSpecPodFailurePolicyRules rulesItem) {
    this.rules.add(rulesItem);
    return this;
  }

   /**
   * Get rules
   * @return rules
  **/
  @ApiModelProperty(required = true, value = "")

  public List<V1alpha1AnalysisTemplateSpecProviderJobSpecPodFailurePolicyRules> getRules() {
    return rules;
  }


  public void setRules(List<V1alpha1AnalysisTemplateSpecProviderJobSpecPodFailurePolicyRules> rules) {
    this.rules = rules;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1AnalysisTemplateSpecProviderJobSpecPodFailurePolicy v1alpha1AnalysisTemplateSpecProviderJobSpecPodFailurePolicy = (V1alpha1AnalysisTemplateSpecProviderJobSpecPodFailurePolicy) o;
    return Objects.equals(this.rules, v1alpha1AnalysisTemplateSpecProviderJobSpecPodFailurePolicy.rules);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rules);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1AnalysisTemplateSpecProviderJobSpecPodFailurePolicy {\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

