/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.models.V1alpha1AnalysisTemplateSpecProviderPrometheusAuthenticationSigv4;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha1AnalysisTemplateSpecProviderPrometheusAuthentication
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-19T02:24:32.086Z[Etc/UTC]")
public class V1alpha1AnalysisTemplateSpecProviderPrometheusAuthentication {
  public static final String SERIALIZED_NAME_SIGV4 = "sigv4";
  @SerializedName(SERIALIZED_NAME_SIGV4)
  private V1alpha1AnalysisTemplateSpecProviderPrometheusAuthenticationSigv4 sigv4;


  public V1alpha1AnalysisTemplateSpecProviderPrometheusAuthentication sigv4(V1alpha1AnalysisTemplateSpecProviderPrometheusAuthenticationSigv4 sigv4) {
    
    this.sigv4 = sigv4;
    return this;
  }

   /**
   * Get sigv4
   * @return sigv4
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1AnalysisTemplateSpecProviderPrometheusAuthenticationSigv4 getSigv4() {
    return sigv4;
  }


  public void setSigv4(V1alpha1AnalysisTemplateSpecProviderPrometheusAuthenticationSigv4 sigv4) {
    this.sigv4 = sigv4;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1AnalysisTemplateSpecProviderPrometheusAuthentication v1alpha1AnalysisTemplateSpecProviderPrometheusAuthentication = (V1alpha1AnalysisTemplateSpecProviderPrometheusAuthentication) o;
    return Objects.equals(this.sigv4, v1alpha1AnalysisTemplateSpecProviderPrometheusAuthentication.sigv4);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sigv4);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1AnalysisTemplateSpecProviderPrometheusAuthentication {\n");
    sb.append("    sigv4: ").append(toIndentedString(sigv4)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

