/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.models.V1alpha1CloudWatchMetricDataQuery;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * CloudWatchMetric defines the cloudwatch query to perform canary analysis
 */
@ApiModel(description = "CloudWatchMetric defines the cloudwatch query to perform canary analysis")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-19T21:57:47.017Z[Etc/UTC]")
public class V1alpha1CloudWatchMetric {
  public static final String SERIALIZED_NAME_INTERVAL = "interval";
  @SerializedName(SERIALIZED_NAME_INTERVAL)
  private String interval;

  public static final String SERIALIZED_NAME_METRIC_DATA_QUERIES = "metricDataQueries";
  @SerializedName(SERIALIZED_NAME_METRIC_DATA_QUERIES)
  private List<V1alpha1CloudWatchMetricDataQuery> metricDataQueries = new ArrayList<>();


  public V1alpha1CloudWatchMetric interval(String interval) {
    
    this.interval = interval;
    return this;
  }

   /**
   * Get interval
   * @return interval
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getInterval() {
    return interval;
  }


  public void setInterval(String interval) {
    this.interval = interval;
  }


  public V1alpha1CloudWatchMetric metricDataQueries(List<V1alpha1CloudWatchMetricDataQuery> metricDataQueries) {
    
    this.metricDataQueries = metricDataQueries;
    return this;
  }

  public V1alpha1CloudWatchMetric addMetricDataQueriesItem(V1alpha1CloudWatchMetricDataQuery metricDataQueriesItem) {
    this.metricDataQueries.add(metricDataQueriesItem);
    return this;
  }

   /**
   * Get metricDataQueries
   * @return metricDataQueries
  **/
  @ApiModelProperty(required = true, value = "")

  public List<V1alpha1CloudWatchMetricDataQuery> getMetricDataQueries() {
    return metricDataQueries;
  }


  public void setMetricDataQueries(List<V1alpha1CloudWatchMetricDataQuery> metricDataQueries) {
    this.metricDataQueries = metricDataQueries;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1CloudWatchMetric v1alpha1CloudWatchMetric = (V1alpha1CloudWatchMetric) o;
    return Objects.equals(this.interval, v1alpha1CloudWatchMetric.interval) &&
        Objects.equals(this.metricDataQueries, v1alpha1CloudWatchMetric.metricDataQueries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(interval, metricDataQueries);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1CloudWatchMetric {\n");
    sb.append("    interval: ").append(toIndentedString(interval)).append("\n");
    sb.append("    metricDataQueries: ").append(toIndentedString(metricDataQueries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

