/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.models.V1alpha1AnalysisTemplateSpecDryRun;
import io.argoproj.models.V1alpha1AnalysisTemplateSpecMeasurementRetention;
import io.argoproj.models.V1alpha1ExperimentSpecAnalyses;
import io.argoproj.models.V1alpha1ExperimentSpecTemplates;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha1ExperimentSpec
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-19T02:24:32.086Z[Etc/UTC]")
public class V1alpha1ExperimentSpec {
  public static final String SERIALIZED_NAME_ANALYSES = "analyses";
  @SerializedName(SERIALIZED_NAME_ANALYSES)
  private List<V1alpha1ExperimentSpecAnalyses> analyses = null;

  public static final String SERIALIZED_NAME_DRY_RUN = "dryRun";
  @SerializedName(SERIALIZED_NAME_DRY_RUN)
  private List<V1alpha1AnalysisTemplateSpecDryRun> dryRun = null;

  public static final String SERIALIZED_NAME_DURATION = "duration";
  @SerializedName(SERIALIZED_NAME_DURATION)
  private String duration;

  public static final String SERIALIZED_NAME_MEASUREMENT_RETENTION = "measurementRetention";
  @SerializedName(SERIALIZED_NAME_MEASUREMENT_RETENTION)
  private List<V1alpha1AnalysisTemplateSpecMeasurementRetention> measurementRetention = null;

  public static final String SERIALIZED_NAME_PROGRESS_DEADLINE_SECONDS = "progressDeadlineSeconds";
  @SerializedName(SERIALIZED_NAME_PROGRESS_DEADLINE_SECONDS)
  private Integer progressDeadlineSeconds;

  public static final String SERIALIZED_NAME_SCALE_DOWN_DELAY_SECONDS = "scaleDownDelaySeconds";
  @SerializedName(SERIALIZED_NAME_SCALE_DOWN_DELAY_SECONDS)
  private Integer scaleDownDelaySeconds;

  public static final String SERIALIZED_NAME_TEMPLATES = "templates";
  @SerializedName(SERIALIZED_NAME_TEMPLATES)
  private List<V1alpha1ExperimentSpecTemplates> templates = new ArrayList<>();

  public static final String SERIALIZED_NAME_TERMINATE = "terminate";
  @SerializedName(SERIALIZED_NAME_TERMINATE)
  private Boolean terminate;


  public V1alpha1ExperimentSpec analyses(List<V1alpha1ExperimentSpecAnalyses> analyses) {
    
    this.analyses = analyses;
    return this;
  }

  public V1alpha1ExperimentSpec addAnalysesItem(V1alpha1ExperimentSpecAnalyses analysesItem) {
    if (this.analyses == null) {
      this.analyses = new ArrayList<>();
    }
    this.analyses.add(analysesItem);
    return this;
  }

   /**
   * Get analyses
   * @return analyses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1ExperimentSpecAnalyses> getAnalyses() {
    return analyses;
  }


  public void setAnalyses(List<V1alpha1ExperimentSpecAnalyses> analyses) {
    this.analyses = analyses;
  }


  public V1alpha1ExperimentSpec dryRun(List<V1alpha1AnalysisTemplateSpecDryRun> dryRun) {
    
    this.dryRun = dryRun;
    return this;
  }

  public V1alpha1ExperimentSpec addDryRunItem(V1alpha1AnalysisTemplateSpecDryRun dryRunItem) {
    if (this.dryRun == null) {
      this.dryRun = new ArrayList<>();
    }
    this.dryRun.add(dryRunItem);
    return this;
  }

   /**
   * Get dryRun
   * @return dryRun
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1AnalysisTemplateSpecDryRun> getDryRun() {
    return dryRun;
  }


  public void setDryRun(List<V1alpha1AnalysisTemplateSpecDryRun> dryRun) {
    this.dryRun = dryRun;
  }


  public V1alpha1ExperimentSpec duration(String duration) {
    
    this.duration = duration;
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDuration() {
    return duration;
  }


  public void setDuration(String duration) {
    this.duration = duration;
  }


  public V1alpha1ExperimentSpec measurementRetention(List<V1alpha1AnalysisTemplateSpecMeasurementRetention> measurementRetention) {
    
    this.measurementRetention = measurementRetention;
    return this;
  }

  public V1alpha1ExperimentSpec addMeasurementRetentionItem(V1alpha1AnalysisTemplateSpecMeasurementRetention measurementRetentionItem) {
    if (this.measurementRetention == null) {
      this.measurementRetention = new ArrayList<>();
    }
    this.measurementRetention.add(measurementRetentionItem);
    return this;
  }

   /**
   * Get measurementRetention
   * @return measurementRetention
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1AnalysisTemplateSpecMeasurementRetention> getMeasurementRetention() {
    return measurementRetention;
  }


  public void setMeasurementRetention(List<V1alpha1AnalysisTemplateSpecMeasurementRetention> measurementRetention) {
    this.measurementRetention = measurementRetention;
  }


  public V1alpha1ExperimentSpec progressDeadlineSeconds(Integer progressDeadlineSeconds) {
    
    this.progressDeadlineSeconds = progressDeadlineSeconds;
    return this;
  }

   /**
   * Get progressDeadlineSeconds
   * @return progressDeadlineSeconds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getProgressDeadlineSeconds() {
    return progressDeadlineSeconds;
  }


  public void setProgressDeadlineSeconds(Integer progressDeadlineSeconds) {
    this.progressDeadlineSeconds = progressDeadlineSeconds;
  }


  public V1alpha1ExperimentSpec scaleDownDelaySeconds(Integer scaleDownDelaySeconds) {
    
    this.scaleDownDelaySeconds = scaleDownDelaySeconds;
    return this;
  }

   /**
   * Get scaleDownDelaySeconds
   * @return scaleDownDelaySeconds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getScaleDownDelaySeconds() {
    return scaleDownDelaySeconds;
  }


  public void setScaleDownDelaySeconds(Integer scaleDownDelaySeconds) {
    this.scaleDownDelaySeconds = scaleDownDelaySeconds;
  }


  public V1alpha1ExperimentSpec templates(List<V1alpha1ExperimentSpecTemplates> templates) {
    
    this.templates = templates;
    return this;
  }

  public V1alpha1ExperimentSpec addTemplatesItem(V1alpha1ExperimentSpecTemplates templatesItem) {
    this.templates.add(templatesItem);
    return this;
  }

   /**
   * Get templates
   * @return templates
  **/
  @ApiModelProperty(required = true, value = "")

  public List<V1alpha1ExperimentSpecTemplates> getTemplates() {
    return templates;
  }


  public void setTemplates(List<V1alpha1ExperimentSpecTemplates> templates) {
    this.templates = templates;
  }


  public V1alpha1ExperimentSpec terminate(Boolean terminate) {
    
    this.terminate = terminate;
    return this;
  }

   /**
   * Get terminate
   * @return terminate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getTerminate() {
    return terminate;
  }


  public void setTerminate(Boolean terminate) {
    this.terminate = terminate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1ExperimentSpec v1alpha1ExperimentSpec = (V1alpha1ExperimentSpec) o;
    return Objects.equals(this.analyses, v1alpha1ExperimentSpec.analyses) &&
        Objects.equals(this.dryRun, v1alpha1ExperimentSpec.dryRun) &&
        Objects.equals(this.duration, v1alpha1ExperimentSpec.duration) &&
        Objects.equals(this.measurementRetention, v1alpha1ExperimentSpec.measurementRetention) &&
        Objects.equals(this.progressDeadlineSeconds, v1alpha1ExperimentSpec.progressDeadlineSeconds) &&
        Objects.equals(this.scaleDownDelaySeconds, v1alpha1ExperimentSpec.scaleDownDelaySeconds) &&
        Objects.equals(this.templates, v1alpha1ExperimentSpec.templates) &&
        Objects.equals(this.terminate, v1alpha1ExperimentSpec.terminate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(analyses, dryRun, duration, measurementRetention, progressDeadlineSeconds, scaleDownDelaySeconds, templates, terminate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1ExperimentSpec {\n");
    sb.append("    analyses: ").append(toIndentedString(analyses)).append("\n");
    sb.append("    dryRun: ").append(toIndentedString(dryRun)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    measurementRetention: ").append(toIndentedString(measurementRetention)).append("\n");
    sb.append("    progressDeadlineSeconds: ").append(toIndentedString(progressDeadlineSeconds)).append("\n");
    sb.append("    scaleDownDelaySeconds: ").append(toIndentedString(scaleDownDelaySeconds)).append("\n");
    sb.append("    templates: ").append(toIndentedString(templates)).append("\n");
    sb.append("    terminate: ").append(toIndentedString(terminate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

