/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.models.V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualServiceTcpRoutes;
import io.argoproj.models.V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualServiceTlsRoutes;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualService
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-19T02:24:32.086Z[Etc/UTC]")
public class V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualService {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_ROUTES = "routes";
  @SerializedName(SERIALIZED_NAME_ROUTES)
  private List<String> routes = null;

  public static final String SERIALIZED_NAME_TCP_ROUTES = "tcpRoutes";
  @SerializedName(SERIALIZED_NAME_TCP_ROUTES)
  private List<V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualServiceTcpRoutes> tcpRoutes = null;

  public static final String SERIALIZED_NAME_TLS_ROUTES = "tlsRoutes";
  @SerializedName(SERIALIZED_NAME_TLS_ROUTES)
  private List<V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualServiceTlsRoutes> tlsRoutes = null;


  public V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualService name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualService routes(List<String> routes) {
    
    this.routes = routes;
    return this;
  }

  public V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualService addRoutesItem(String routesItem) {
    if (this.routes == null) {
      this.routes = new ArrayList<>();
    }
    this.routes.add(routesItem);
    return this;
  }

   /**
   * Get routes
   * @return routes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getRoutes() {
    return routes;
  }


  public void setRoutes(List<String> routes) {
    this.routes = routes;
  }


  public V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualService tcpRoutes(List<V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualServiceTcpRoutes> tcpRoutes) {
    
    this.tcpRoutes = tcpRoutes;
    return this;
  }

  public V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualService addTcpRoutesItem(V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualServiceTcpRoutes tcpRoutesItem) {
    if (this.tcpRoutes == null) {
      this.tcpRoutes = new ArrayList<>();
    }
    this.tcpRoutes.add(tcpRoutesItem);
    return this;
  }

   /**
   * Get tcpRoutes
   * @return tcpRoutes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualServiceTcpRoutes> getTcpRoutes() {
    return tcpRoutes;
  }


  public void setTcpRoutes(List<V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualServiceTcpRoutes> tcpRoutes) {
    this.tcpRoutes = tcpRoutes;
  }


  public V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualService tlsRoutes(List<V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualServiceTlsRoutes> tlsRoutes) {
    
    this.tlsRoutes = tlsRoutes;
    return this;
  }

  public V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualService addTlsRoutesItem(V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualServiceTlsRoutes tlsRoutesItem) {
    if (this.tlsRoutes == null) {
      this.tlsRoutes = new ArrayList<>();
    }
    this.tlsRoutes.add(tlsRoutesItem);
    return this;
  }

   /**
   * Get tlsRoutes
   * @return tlsRoutes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualServiceTlsRoutes> getTlsRoutes() {
    return tlsRoutes;
  }


  public void setTlsRoutes(List<V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualServiceTlsRoutes> tlsRoutes) {
    this.tlsRoutes = tlsRoutes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualService v1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualService = (V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualService) o;
    return Objects.equals(this.name, v1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualService.name) &&
        Objects.equals(this.routes, v1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualService.routes) &&
        Objects.equals(this.tcpRoutes, v1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualService.tcpRoutes) &&
        Objects.equals(this.tlsRoutes, v1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualService.tlsRoutes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, routes, tcpRoutes, tlsRoutes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualService {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    routes: ").append(toIndentedString(routes)).append("\n");
    sb.append("    tcpRoutes: ").append(toIndentedString(tcpRoutes)).append("\n");
    sb.append("    tlsRoutes: ").append(toIndentedString(tlsRoutes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

