/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ApisixRoute holds information on the APISIX Route the rollout needs to modify
 */
@ApiModel(description = "ApisixRoute holds information on the APISIX Route the rollout needs to modify")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-19T21:57:47.017Z[Etc/UTC]")
public class V1alpha1ApisixRoute {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name = "";

  public static final String SERIALIZED_NAME_RULES = "rules";
  @SerializedName(SERIALIZED_NAME_RULES)
  private List<String> rules = null;


  public V1alpha1ApisixRoute name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name refer to the name of the APISIX Route used to route traffic to the service
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name refer to the name of the APISIX Route used to route traffic to the service")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1alpha1ApisixRoute rules(List<String> rules) {
    
    this.rules = rules;
    return this;
  }

  public V1alpha1ApisixRoute addRulesItem(String rulesItem) {
    if (this.rules == null) {
      this.rules = new ArrayList<>();
    }
    this.rules.add(rulesItem);
    return this;
  }

   /**
   * RuleRef a list of the APISIX Route HTTP Rules used to route traffic to the service
   * @return rules
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "RuleRef a list of the APISIX Route HTTP Rules used to route traffic to the service")

  public List<String> getRules() {
    return rules;
  }


  public void setRules(List<String> rules) {
    this.rules = rules;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1ApisixRoute v1alpha1ApisixRoute = (V1alpha1ApisixRoute) o;
    return Objects.equals(this.name, v1alpha1ApisixRoute.name) &&
        Objects.equals(this.rules, v1alpha1ApisixRoute.rules);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, rules);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1ApisixRoute {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

