/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.models.V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecAffinity;
import io.argoproj.models.V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecContainers;
import io.argoproj.models.V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecDnsConfig;
import io.argoproj.models.V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecEphemeralContainers;
import io.argoproj.models.V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecHostAliases;
import io.argoproj.models.V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecImagePullSecrets;
import io.argoproj.models.V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecOs;
import io.argoproj.models.V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecReadinessGates;
import io.argoproj.models.V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecSecurityContext1;
import io.argoproj.models.V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecTolerations;
import io.argoproj.models.V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecTopologySpreadConstraints;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * V1alpha1RolloutSpecTemplateSpec
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-19T02:24:32.086Z[Etc/UTC]")
public class V1alpha1RolloutSpecTemplateSpec {
  public static final String SERIALIZED_NAME_ACTIVE_DEADLINE_SECONDS = "activeDeadlineSeconds";
  @SerializedName(SERIALIZED_NAME_ACTIVE_DEADLINE_SECONDS)
  private Long activeDeadlineSeconds;

  public static final String SERIALIZED_NAME_AFFINITY = "affinity";
  @SerializedName(SERIALIZED_NAME_AFFINITY)
  private V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecAffinity affinity;

  public static final String SERIALIZED_NAME_AUTOMOUNT_SERVICE_ACCOUNT_TOKEN = "automountServiceAccountToken";
  @SerializedName(SERIALIZED_NAME_AUTOMOUNT_SERVICE_ACCOUNT_TOKEN)
  private Boolean automountServiceAccountToken;

  public static final String SERIALIZED_NAME_CONTAINERS = "containers";
  @SerializedName(SERIALIZED_NAME_CONTAINERS)
  private List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecContainers> containers = new ArrayList<>();

  public static final String SERIALIZED_NAME_DNS_CONFIG = "dnsConfig";
  @SerializedName(SERIALIZED_NAME_DNS_CONFIG)
  private V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecDnsConfig dnsConfig;

  public static final String SERIALIZED_NAME_DNS_POLICY = "dnsPolicy";
  @SerializedName(SERIALIZED_NAME_DNS_POLICY)
  private String dnsPolicy;

  public static final String SERIALIZED_NAME_ENABLE_SERVICE_LINKS = "enableServiceLinks";
  @SerializedName(SERIALIZED_NAME_ENABLE_SERVICE_LINKS)
  private Boolean enableServiceLinks;

  public static final String SERIALIZED_NAME_EPHEMERAL_CONTAINERS = "ephemeralContainers";
  @SerializedName(SERIALIZED_NAME_EPHEMERAL_CONTAINERS)
  private List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecEphemeralContainers> ephemeralContainers = null;

  public static final String SERIALIZED_NAME_HOST_ALIASES = "hostAliases";
  @SerializedName(SERIALIZED_NAME_HOST_ALIASES)
  private List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecHostAliases> hostAliases = null;

  public static final String SERIALIZED_NAME_HOST_I_P_C = "hostIPC";
  @SerializedName(SERIALIZED_NAME_HOST_I_P_C)
  private Boolean hostIPC;

  public static final String SERIALIZED_NAME_HOST_NETWORK = "hostNetwork";
  @SerializedName(SERIALIZED_NAME_HOST_NETWORK)
  private Boolean hostNetwork;

  public static final String SERIALIZED_NAME_HOST_P_I_D = "hostPID";
  @SerializedName(SERIALIZED_NAME_HOST_P_I_D)
  private Boolean hostPID;

  public static final String SERIALIZED_NAME_HOST_USERS = "hostUsers";
  @SerializedName(SERIALIZED_NAME_HOST_USERS)
  private Boolean hostUsers;

  public static final String SERIALIZED_NAME_HOSTNAME = "hostname";
  @SerializedName(SERIALIZED_NAME_HOSTNAME)
  private String hostname;

  public static final String SERIALIZED_NAME_IMAGE_PULL_SECRETS = "imagePullSecrets";
  @SerializedName(SERIALIZED_NAME_IMAGE_PULL_SECRETS)
  private List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecImagePullSecrets> imagePullSecrets = null;

  public static final String SERIALIZED_NAME_INIT_CONTAINERS = "initContainers";
  @SerializedName(SERIALIZED_NAME_INIT_CONTAINERS)
  private List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecContainers> initContainers = null;

  public static final String SERIALIZED_NAME_NODE_NAME = "nodeName";
  @SerializedName(SERIALIZED_NAME_NODE_NAME)
  private String nodeName;

  public static final String SERIALIZED_NAME_NODE_SELECTOR = "nodeSelector";
  @SerializedName(SERIALIZED_NAME_NODE_SELECTOR)
  private Map<String, String> nodeSelector = null;

  public static final String SERIALIZED_NAME_OS = "os";
  @SerializedName(SERIALIZED_NAME_OS)
  private V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecOs os;

  public static final String SERIALIZED_NAME_OVERHEAD = "overhead";
  @SerializedName(SERIALIZED_NAME_OVERHEAD)
  private Map<String, Object> overhead = null;

  public static final String SERIALIZED_NAME_PREEMPTION_POLICY = "preemptionPolicy";
  @SerializedName(SERIALIZED_NAME_PREEMPTION_POLICY)
  private String preemptionPolicy;

  public static final String SERIALIZED_NAME_PRIORITY = "priority";
  @SerializedName(SERIALIZED_NAME_PRIORITY)
  private Integer priority;

  public static final String SERIALIZED_NAME_PRIORITY_CLASS_NAME = "priorityClassName";
  @SerializedName(SERIALIZED_NAME_PRIORITY_CLASS_NAME)
  private String priorityClassName;

  public static final String SERIALIZED_NAME_READINESS_GATES = "readinessGates";
  @SerializedName(SERIALIZED_NAME_READINESS_GATES)
  private List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecReadinessGates> readinessGates = null;

  public static final String SERIALIZED_NAME_RESTART_POLICY = "restartPolicy";
  @SerializedName(SERIALIZED_NAME_RESTART_POLICY)
  private String restartPolicy;

  public static final String SERIALIZED_NAME_RUNTIME_CLASS_NAME = "runtimeClassName";
  @SerializedName(SERIALIZED_NAME_RUNTIME_CLASS_NAME)
  private String runtimeClassName;

  public static final String SERIALIZED_NAME_SCHEDULER_NAME = "schedulerName";
  @SerializedName(SERIALIZED_NAME_SCHEDULER_NAME)
  private String schedulerName;

  public static final String SERIALIZED_NAME_SECURITY_CONTEXT = "securityContext";
  @SerializedName(SERIALIZED_NAME_SECURITY_CONTEXT)
  private V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecSecurityContext1 securityContext;

  public static final String SERIALIZED_NAME_SERVICE_ACCOUNT = "serviceAccount";
  @SerializedName(SERIALIZED_NAME_SERVICE_ACCOUNT)
  private String serviceAccount;

  public static final String SERIALIZED_NAME_SERVICE_ACCOUNT_NAME = "serviceAccountName";
  @SerializedName(SERIALIZED_NAME_SERVICE_ACCOUNT_NAME)
  private String serviceAccountName;

  public static final String SERIALIZED_NAME_SET_HOSTNAME_AS_F_Q_D_N = "setHostnameAsFQDN";
  @SerializedName(SERIALIZED_NAME_SET_HOSTNAME_AS_F_Q_D_N)
  private Boolean setHostnameAsFQDN;

  public static final String SERIALIZED_NAME_SHARE_PROCESS_NAMESPACE = "shareProcessNamespace";
  @SerializedName(SERIALIZED_NAME_SHARE_PROCESS_NAMESPACE)
  private Boolean shareProcessNamespace;

  public static final String SERIALIZED_NAME_SUBDOMAIN = "subdomain";
  @SerializedName(SERIALIZED_NAME_SUBDOMAIN)
  private String subdomain;

  public static final String SERIALIZED_NAME_TERMINATION_GRACE_PERIOD_SECONDS = "terminationGracePeriodSeconds";
  @SerializedName(SERIALIZED_NAME_TERMINATION_GRACE_PERIOD_SECONDS)
  private Long terminationGracePeriodSeconds;

  public static final String SERIALIZED_NAME_TOLERATIONS = "tolerations";
  @SerializedName(SERIALIZED_NAME_TOLERATIONS)
  private List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecTolerations> tolerations = null;

  public static final String SERIALIZED_NAME_TOPOLOGY_SPREAD_CONSTRAINTS = "topologySpreadConstraints";
  @SerializedName(SERIALIZED_NAME_TOPOLOGY_SPREAD_CONSTRAINTS)
  private List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecTopologySpreadConstraints> topologySpreadConstraints = null;

  public static final String SERIALIZED_NAME_VOLUMES = "volumes";
  @SerializedName(SERIALIZED_NAME_VOLUMES)
  private List<Object> volumes = null;


  public V1alpha1RolloutSpecTemplateSpec activeDeadlineSeconds(Long activeDeadlineSeconds) {
    
    this.activeDeadlineSeconds = activeDeadlineSeconds;
    return this;
  }

   /**
   * Get activeDeadlineSeconds
   * @return activeDeadlineSeconds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getActiveDeadlineSeconds() {
    return activeDeadlineSeconds;
  }


  public void setActiveDeadlineSeconds(Long activeDeadlineSeconds) {
    this.activeDeadlineSeconds = activeDeadlineSeconds;
  }


  public V1alpha1RolloutSpecTemplateSpec affinity(V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecAffinity affinity) {
    
    this.affinity = affinity;
    return this;
  }

   /**
   * Get affinity
   * @return affinity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecAffinity getAffinity() {
    return affinity;
  }


  public void setAffinity(V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecAffinity affinity) {
    this.affinity = affinity;
  }


  public V1alpha1RolloutSpecTemplateSpec automountServiceAccountToken(Boolean automountServiceAccountToken) {
    
    this.automountServiceAccountToken = automountServiceAccountToken;
    return this;
  }

   /**
   * Get automountServiceAccountToken
   * @return automountServiceAccountToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getAutomountServiceAccountToken() {
    return automountServiceAccountToken;
  }


  public void setAutomountServiceAccountToken(Boolean automountServiceAccountToken) {
    this.automountServiceAccountToken = automountServiceAccountToken;
  }


  public V1alpha1RolloutSpecTemplateSpec containers(List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecContainers> containers) {
    
    this.containers = containers;
    return this;
  }

  public V1alpha1RolloutSpecTemplateSpec addContainersItem(V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecContainers containersItem) {
    this.containers.add(containersItem);
    return this;
  }

   /**
   * Get containers
   * @return containers
  **/
  @ApiModelProperty(required = true, value = "")

  public List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecContainers> getContainers() {
    return containers;
  }


  public void setContainers(List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecContainers> containers) {
    this.containers = containers;
  }


  public V1alpha1RolloutSpecTemplateSpec dnsConfig(V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecDnsConfig dnsConfig) {
    
    this.dnsConfig = dnsConfig;
    return this;
  }

   /**
   * Get dnsConfig
   * @return dnsConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecDnsConfig getDnsConfig() {
    return dnsConfig;
  }


  public void setDnsConfig(V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecDnsConfig dnsConfig) {
    this.dnsConfig = dnsConfig;
  }


  public V1alpha1RolloutSpecTemplateSpec dnsPolicy(String dnsPolicy) {
    
    this.dnsPolicy = dnsPolicy;
    return this;
  }

   /**
   * Get dnsPolicy
   * @return dnsPolicy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDnsPolicy() {
    return dnsPolicy;
  }


  public void setDnsPolicy(String dnsPolicy) {
    this.dnsPolicy = dnsPolicy;
  }


  public V1alpha1RolloutSpecTemplateSpec enableServiceLinks(Boolean enableServiceLinks) {
    
    this.enableServiceLinks = enableServiceLinks;
    return this;
  }

   /**
   * Get enableServiceLinks
   * @return enableServiceLinks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getEnableServiceLinks() {
    return enableServiceLinks;
  }


  public void setEnableServiceLinks(Boolean enableServiceLinks) {
    this.enableServiceLinks = enableServiceLinks;
  }


  public V1alpha1RolloutSpecTemplateSpec ephemeralContainers(List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecEphemeralContainers> ephemeralContainers) {
    
    this.ephemeralContainers = ephemeralContainers;
    return this;
  }

  public V1alpha1RolloutSpecTemplateSpec addEphemeralContainersItem(V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecEphemeralContainers ephemeralContainersItem) {
    if (this.ephemeralContainers == null) {
      this.ephemeralContainers = new ArrayList<>();
    }
    this.ephemeralContainers.add(ephemeralContainersItem);
    return this;
  }

   /**
   * Get ephemeralContainers
   * @return ephemeralContainers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecEphemeralContainers> getEphemeralContainers() {
    return ephemeralContainers;
  }


  public void setEphemeralContainers(List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecEphemeralContainers> ephemeralContainers) {
    this.ephemeralContainers = ephemeralContainers;
  }


  public V1alpha1RolloutSpecTemplateSpec hostAliases(List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecHostAliases> hostAliases) {
    
    this.hostAliases = hostAliases;
    return this;
  }

  public V1alpha1RolloutSpecTemplateSpec addHostAliasesItem(V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecHostAliases hostAliasesItem) {
    if (this.hostAliases == null) {
      this.hostAliases = new ArrayList<>();
    }
    this.hostAliases.add(hostAliasesItem);
    return this;
  }

   /**
   * Get hostAliases
   * @return hostAliases
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecHostAliases> getHostAliases() {
    return hostAliases;
  }


  public void setHostAliases(List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecHostAliases> hostAliases) {
    this.hostAliases = hostAliases;
  }


  public V1alpha1RolloutSpecTemplateSpec hostIPC(Boolean hostIPC) {
    
    this.hostIPC = hostIPC;
    return this;
  }

   /**
   * Get hostIPC
   * @return hostIPC
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getHostIPC() {
    return hostIPC;
  }


  public void setHostIPC(Boolean hostIPC) {
    this.hostIPC = hostIPC;
  }


  public V1alpha1RolloutSpecTemplateSpec hostNetwork(Boolean hostNetwork) {
    
    this.hostNetwork = hostNetwork;
    return this;
  }

   /**
   * Get hostNetwork
   * @return hostNetwork
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getHostNetwork() {
    return hostNetwork;
  }


  public void setHostNetwork(Boolean hostNetwork) {
    this.hostNetwork = hostNetwork;
  }


  public V1alpha1RolloutSpecTemplateSpec hostPID(Boolean hostPID) {
    
    this.hostPID = hostPID;
    return this;
  }

   /**
   * Get hostPID
   * @return hostPID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getHostPID() {
    return hostPID;
  }


  public void setHostPID(Boolean hostPID) {
    this.hostPID = hostPID;
  }


  public V1alpha1RolloutSpecTemplateSpec hostUsers(Boolean hostUsers) {
    
    this.hostUsers = hostUsers;
    return this;
  }

   /**
   * Get hostUsers
   * @return hostUsers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getHostUsers() {
    return hostUsers;
  }


  public void setHostUsers(Boolean hostUsers) {
    this.hostUsers = hostUsers;
  }


  public V1alpha1RolloutSpecTemplateSpec hostname(String hostname) {
    
    this.hostname = hostname;
    return this;
  }

   /**
   * Get hostname
   * @return hostname
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHostname() {
    return hostname;
  }


  public void setHostname(String hostname) {
    this.hostname = hostname;
  }


  public V1alpha1RolloutSpecTemplateSpec imagePullSecrets(List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecImagePullSecrets> imagePullSecrets) {
    
    this.imagePullSecrets = imagePullSecrets;
    return this;
  }

  public V1alpha1RolloutSpecTemplateSpec addImagePullSecretsItem(V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecImagePullSecrets imagePullSecretsItem) {
    if (this.imagePullSecrets == null) {
      this.imagePullSecrets = new ArrayList<>();
    }
    this.imagePullSecrets.add(imagePullSecretsItem);
    return this;
  }

   /**
   * Get imagePullSecrets
   * @return imagePullSecrets
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecImagePullSecrets> getImagePullSecrets() {
    return imagePullSecrets;
  }


  public void setImagePullSecrets(List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecImagePullSecrets> imagePullSecrets) {
    this.imagePullSecrets = imagePullSecrets;
  }


  public V1alpha1RolloutSpecTemplateSpec initContainers(List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecContainers> initContainers) {
    
    this.initContainers = initContainers;
    return this;
  }

  public V1alpha1RolloutSpecTemplateSpec addInitContainersItem(V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecContainers initContainersItem) {
    if (this.initContainers == null) {
      this.initContainers = new ArrayList<>();
    }
    this.initContainers.add(initContainersItem);
    return this;
  }

   /**
   * Get initContainers
   * @return initContainers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecContainers> getInitContainers() {
    return initContainers;
  }


  public void setInitContainers(List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecContainers> initContainers) {
    this.initContainers = initContainers;
  }


  public V1alpha1RolloutSpecTemplateSpec nodeName(String nodeName) {
    
    this.nodeName = nodeName;
    return this;
  }

   /**
   * Get nodeName
   * @return nodeName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNodeName() {
    return nodeName;
  }


  public void setNodeName(String nodeName) {
    this.nodeName = nodeName;
  }


  public V1alpha1RolloutSpecTemplateSpec nodeSelector(Map<String, String> nodeSelector) {
    
    this.nodeSelector = nodeSelector;
    return this;
  }

  public V1alpha1RolloutSpecTemplateSpec putNodeSelectorItem(String key, String nodeSelectorItem) {
    if (this.nodeSelector == null) {
      this.nodeSelector = new HashMap<>();
    }
    this.nodeSelector.put(key, nodeSelectorItem);
    return this;
  }

   /**
   * Get nodeSelector
   * @return nodeSelector
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, String> getNodeSelector() {
    return nodeSelector;
  }


  public void setNodeSelector(Map<String, String> nodeSelector) {
    this.nodeSelector = nodeSelector;
  }


  public V1alpha1RolloutSpecTemplateSpec os(V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecOs os) {
    
    this.os = os;
    return this;
  }

   /**
   * Get os
   * @return os
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecOs getOs() {
    return os;
  }


  public void setOs(V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecOs os) {
    this.os = os;
  }


  public V1alpha1RolloutSpecTemplateSpec overhead(Map<String, Object> overhead) {
    
    this.overhead = overhead;
    return this;
  }

  public V1alpha1RolloutSpecTemplateSpec putOverheadItem(String key, Object overheadItem) {
    if (this.overhead == null) {
      this.overhead = new HashMap<>();
    }
    this.overhead.put(key, overheadItem);
    return this;
  }

   /**
   * Get overhead
   * @return overhead
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, Object> getOverhead() {
    return overhead;
  }


  public void setOverhead(Map<String, Object> overhead) {
    this.overhead = overhead;
  }


  public V1alpha1RolloutSpecTemplateSpec preemptionPolicy(String preemptionPolicy) {
    
    this.preemptionPolicy = preemptionPolicy;
    return this;
  }

   /**
   * Get preemptionPolicy
   * @return preemptionPolicy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPreemptionPolicy() {
    return preemptionPolicy;
  }


  public void setPreemptionPolicy(String preemptionPolicy) {
    this.preemptionPolicy = preemptionPolicy;
  }


  public V1alpha1RolloutSpecTemplateSpec priority(Integer priority) {
    
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getPriority() {
    return priority;
  }


  public void setPriority(Integer priority) {
    this.priority = priority;
  }


  public V1alpha1RolloutSpecTemplateSpec priorityClassName(String priorityClassName) {
    
    this.priorityClassName = priorityClassName;
    return this;
  }

   /**
   * Get priorityClassName
   * @return priorityClassName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPriorityClassName() {
    return priorityClassName;
  }


  public void setPriorityClassName(String priorityClassName) {
    this.priorityClassName = priorityClassName;
  }


  public V1alpha1RolloutSpecTemplateSpec readinessGates(List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecReadinessGates> readinessGates) {
    
    this.readinessGates = readinessGates;
    return this;
  }

  public V1alpha1RolloutSpecTemplateSpec addReadinessGatesItem(V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecReadinessGates readinessGatesItem) {
    if (this.readinessGates == null) {
      this.readinessGates = new ArrayList<>();
    }
    this.readinessGates.add(readinessGatesItem);
    return this;
  }

   /**
   * Get readinessGates
   * @return readinessGates
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecReadinessGates> getReadinessGates() {
    return readinessGates;
  }


  public void setReadinessGates(List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecReadinessGates> readinessGates) {
    this.readinessGates = readinessGates;
  }


  public V1alpha1RolloutSpecTemplateSpec restartPolicy(String restartPolicy) {
    
    this.restartPolicy = restartPolicy;
    return this;
  }

   /**
   * Get restartPolicy
   * @return restartPolicy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRestartPolicy() {
    return restartPolicy;
  }


  public void setRestartPolicy(String restartPolicy) {
    this.restartPolicy = restartPolicy;
  }


  public V1alpha1RolloutSpecTemplateSpec runtimeClassName(String runtimeClassName) {
    
    this.runtimeClassName = runtimeClassName;
    return this;
  }

   /**
   * Get runtimeClassName
   * @return runtimeClassName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRuntimeClassName() {
    return runtimeClassName;
  }


  public void setRuntimeClassName(String runtimeClassName) {
    this.runtimeClassName = runtimeClassName;
  }


  public V1alpha1RolloutSpecTemplateSpec schedulerName(String schedulerName) {
    
    this.schedulerName = schedulerName;
    return this;
  }

   /**
   * Get schedulerName
   * @return schedulerName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSchedulerName() {
    return schedulerName;
  }


  public void setSchedulerName(String schedulerName) {
    this.schedulerName = schedulerName;
  }


  public V1alpha1RolloutSpecTemplateSpec securityContext(V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecSecurityContext1 securityContext) {
    
    this.securityContext = securityContext;
    return this;
  }

   /**
   * Get securityContext
   * @return securityContext
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecSecurityContext1 getSecurityContext() {
    return securityContext;
  }


  public void setSecurityContext(V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecSecurityContext1 securityContext) {
    this.securityContext = securityContext;
  }


  public V1alpha1RolloutSpecTemplateSpec serviceAccount(String serviceAccount) {
    
    this.serviceAccount = serviceAccount;
    return this;
  }

   /**
   * Get serviceAccount
   * @return serviceAccount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getServiceAccount() {
    return serviceAccount;
  }


  public void setServiceAccount(String serviceAccount) {
    this.serviceAccount = serviceAccount;
  }


  public V1alpha1RolloutSpecTemplateSpec serviceAccountName(String serviceAccountName) {
    
    this.serviceAccountName = serviceAccountName;
    return this;
  }

   /**
   * Get serviceAccountName
   * @return serviceAccountName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getServiceAccountName() {
    return serviceAccountName;
  }


  public void setServiceAccountName(String serviceAccountName) {
    this.serviceAccountName = serviceAccountName;
  }


  public V1alpha1RolloutSpecTemplateSpec setHostnameAsFQDN(Boolean setHostnameAsFQDN) {
    
    this.setHostnameAsFQDN = setHostnameAsFQDN;
    return this;
  }

   /**
   * Get setHostnameAsFQDN
   * @return setHostnameAsFQDN
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getSetHostnameAsFQDN() {
    return setHostnameAsFQDN;
  }


  public void setSetHostnameAsFQDN(Boolean setHostnameAsFQDN) {
    this.setHostnameAsFQDN = setHostnameAsFQDN;
  }


  public V1alpha1RolloutSpecTemplateSpec shareProcessNamespace(Boolean shareProcessNamespace) {
    
    this.shareProcessNamespace = shareProcessNamespace;
    return this;
  }

   /**
   * Get shareProcessNamespace
   * @return shareProcessNamespace
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getShareProcessNamespace() {
    return shareProcessNamespace;
  }


  public void setShareProcessNamespace(Boolean shareProcessNamespace) {
    this.shareProcessNamespace = shareProcessNamespace;
  }


  public V1alpha1RolloutSpecTemplateSpec subdomain(String subdomain) {
    
    this.subdomain = subdomain;
    return this;
  }

   /**
   * Get subdomain
   * @return subdomain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSubdomain() {
    return subdomain;
  }


  public void setSubdomain(String subdomain) {
    this.subdomain = subdomain;
  }


  public V1alpha1RolloutSpecTemplateSpec terminationGracePeriodSeconds(Long terminationGracePeriodSeconds) {
    
    this.terminationGracePeriodSeconds = terminationGracePeriodSeconds;
    return this;
  }

   /**
   * Get terminationGracePeriodSeconds
   * @return terminationGracePeriodSeconds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getTerminationGracePeriodSeconds() {
    return terminationGracePeriodSeconds;
  }


  public void setTerminationGracePeriodSeconds(Long terminationGracePeriodSeconds) {
    this.terminationGracePeriodSeconds = terminationGracePeriodSeconds;
  }


  public V1alpha1RolloutSpecTemplateSpec tolerations(List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecTolerations> tolerations) {
    
    this.tolerations = tolerations;
    return this;
  }

  public V1alpha1RolloutSpecTemplateSpec addTolerationsItem(V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecTolerations tolerationsItem) {
    if (this.tolerations == null) {
      this.tolerations = new ArrayList<>();
    }
    this.tolerations.add(tolerationsItem);
    return this;
  }

   /**
   * Get tolerations
   * @return tolerations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecTolerations> getTolerations() {
    return tolerations;
  }


  public void setTolerations(List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecTolerations> tolerations) {
    this.tolerations = tolerations;
  }


  public V1alpha1RolloutSpecTemplateSpec topologySpreadConstraints(List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecTopologySpreadConstraints> topologySpreadConstraints) {
    
    this.topologySpreadConstraints = topologySpreadConstraints;
    return this;
  }

  public V1alpha1RolloutSpecTemplateSpec addTopologySpreadConstraintsItem(V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecTopologySpreadConstraints topologySpreadConstraintsItem) {
    if (this.topologySpreadConstraints == null) {
      this.topologySpreadConstraints = new ArrayList<>();
    }
    this.topologySpreadConstraints.add(topologySpreadConstraintsItem);
    return this;
  }

   /**
   * Get topologySpreadConstraints
   * @return topologySpreadConstraints
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecTopologySpreadConstraints> getTopologySpreadConstraints() {
    return topologySpreadConstraints;
  }


  public void setTopologySpreadConstraints(List<V1alpha1AnalysisTemplateSpecProviderJobSpecTemplateSpecTopologySpreadConstraints> topologySpreadConstraints) {
    this.topologySpreadConstraints = topologySpreadConstraints;
  }


  public V1alpha1RolloutSpecTemplateSpec volumes(List<Object> volumes) {
    
    this.volumes = volumes;
    return this;
  }

  public V1alpha1RolloutSpecTemplateSpec addVolumesItem(Object volumesItem) {
    if (this.volumes == null) {
      this.volumes = new ArrayList<>();
    }
    this.volumes.add(volumesItem);
    return this;
  }

   /**
   * Get volumes
   * @return volumes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Object> getVolumes() {
    return volumes;
  }


  public void setVolumes(List<Object> volumes) {
    this.volumes = volumes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1RolloutSpecTemplateSpec v1alpha1RolloutSpecTemplateSpec = (V1alpha1RolloutSpecTemplateSpec) o;
    return Objects.equals(this.activeDeadlineSeconds, v1alpha1RolloutSpecTemplateSpec.activeDeadlineSeconds) &&
        Objects.equals(this.affinity, v1alpha1RolloutSpecTemplateSpec.affinity) &&
        Objects.equals(this.automountServiceAccountToken, v1alpha1RolloutSpecTemplateSpec.automountServiceAccountToken) &&
        Objects.equals(this.containers, v1alpha1RolloutSpecTemplateSpec.containers) &&
        Objects.equals(this.dnsConfig, v1alpha1RolloutSpecTemplateSpec.dnsConfig) &&
        Objects.equals(this.dnsPolicy, v1alpha1RolloutSpecTemplateSpec.dnsPolicy) &&
        Objects.equals(this.enableServiceLinks, v1alpha1RolloutSpecTemplateSpec.enableServiceLinks) &&
        Objects.equals(this.ephemeralContainers, v1alpha1RolloutSpecTemplateSpec.ephemeralContainers) &&
        Objects.equals(this.hostAliases, v1alpha1RolloutSpecTemplateSpec.hostAliases) &&
        Objects.equals(this.hostIPC, v1alpha1RolloutSpecTemplateSpec.hostIPC) &&
        Objects.equals(this.hostNetwork, v1alpha1RolloutSpecTemplateSpec.hostNetwork) &&
        Objects.equals(this.hostPID, v1alpha1RolloutSpecTemplateSpec.hostPID) &&
        Objects.equals(this.hostUsers, v1alpha1RolloutSpecTemplateSpec.hostUsers) &&
        Objects.equals(this.hostname, v1alpha1RolloutSpecTemplateSpec.hostname) &&
        Objects.equals(this.imagePullSecrets, v1alpha1RolloutSpecTemplateSpec.imagePullSecrets) &&
        Objects.equals(this.initContainers, v1alpha1RolloutSpecTemplateSpec.initContainers) &&
        Objects.equals(this.nodeName, v1alpha1RolloutSpecTemplateSpec.nodeName) &&
        Objects.equals(this.nodeSelector, v1alpha1RolloutSpecTemplateSpec.nodeSelector) &&
        Objects.equals(this.os, v1alpha1RolloutSpecTemplateSpec.os) &&
        Objects.equals(this.overhead, v1alpha1RolloutSpecTemplateSpec.overhead) &&
        Objects.equals(this.preemptionPolicy, v1alpha1RolloutSpecTemplateSpec.preemptionPolicy) &&
        Objects.equals(this.priority, v1alpha1RolloutSpecTemplateSpec.priority) &&
        Objects.equals(this.priorityClassName, v1alpha1RolloutSpecTemplateSpec.priorityClassName) &&
        Objects.equals(this.readinessGates, v1alpha1RolloutSpecTemplateSpec.readinessGates) &&
        Objects.equals(this.restartPolicy, v1alpha1RolloutSpecTemplateSpec.restartPolicy) &&
        Objects.equals(this.runtimeClassName, v1alpha1RolloutSpecTemplateSpec.runtimeClassName) &&
        Objects.equals(this.schedulerName, v1alpha1RolloutSpecTemplateSpec.schedulerName) &&
        Objects.equals(this.securityContext, v1alpha1RolloutSpecTemplateSpec.securityContext) &&
        Objects.equals(this.serviceAccount, v1alpha1RolloutSpecTemplateSpec.serviceAccount) &&
        Objects.equals(this.serviceAccountName, v1alpha1RolloutSpecTemplateSpec.serviceAccountName) &&
        Objects.equals(this.setHostnameAsFQDN, v1alpha1RolloutSpecTemplateSpec.setHostnameAsFQDN) &&
        Objects.equals(this.shareProcessNamespace, v1alpha1RolloutSpecTemplateSpec.shareProcessNamespace) &&
        Objects.equals(this.subdomain, v1alpha1RolloutSpecTemplateSpec.subdomain) &&
        Objects.equals(this.terminationGracePeriodSeconds, v1alpha1RolloutSpecTemplateSpec.terminationGracePeriodSeconds) &&
        Objects.equals(this.tolerations, v1alpha1RolloutSpecTemplateSpec.tolerations) &&
        Objects.equals(this.topologySpreadConstraints, v1alpha1RolloutSpecTemplateSpec.topologySpreadConstraints) &&
        Objects.equals(this.volumes, v1alpha1RolloutSpecTemplateSpec.volumes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(activeDeadlineSeconds, affinity, automountServiceAccountToken, containers, dnsConfig, dnsPolicy, enableServiceLinks, ephemeralContainers, hostAliases, hostIPC, hostNetwork, hostPID, hostUsers, hostname, imagePullSecrets, initContainers, nodeName, nodeSelector, os, overhead, preemptionPolicy, priority, priorityClassName, readinessGates, restartPolicy, runtimeClassName, schedulerName, securityContext, serviceAccount, serviceAccountName, setHostnameAsFQDN, shareProcessNamespace, subdomain, terminationGracePeriodSeconds, tolerations, topologySpreadConstraints, volumes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1RolloutSpecTemplateSpec {\n");
    sb.append("    activeDeadlineSeconds: ").append(toIndentedString(activeDeadlineSeconds)).append("\n");
    sb.append("    affinity: ").append(toIndentedString(affinity)).append("\n");
    sb.append("    automountServiceAccountToken: ").append(toIndentedString(automountServiceAccountToken)).append("\n");
    sb.append("    containers: ").append(toIndentedString(containers)).append("\n");
    sb.append("    dnsConfig: ").append(toIndentedString(dnsConfig)).append("\n");
    sb.append("    dnsPolicy: ").append(toIndentedString(dnsPolicy)).append("\n");
    sb.append("    enableServiceLinks: ").append(toIndentedString(enableServiceLinks)).append("\n");
    sb.append("    ephemeralContainers: ").append(toIndentedString(ephemeralContainers)).append("\n");
    sb.append("    hostAliases: ").append(toIndentedString(hostAliases)).append("\n");
    sb.append("    hostIPC: ").append(toIndentedString(hostIPC)).append("\n");
    sb.append("    hostNetwork: ").append(toIndentedString(hostNetwork)).append("\n");
    sb.append("    hostPID: ").append(toIndentedString(hostPID)).append("\n");
    sb.append("    hostUsers: ").append(toIndentedString(hostUsers)).append("\n");
    sb.append("    hostname: ").append(toIndentedString(hostname)).append("\n");
    sb.append("    imagePullSecrets: ").append(toIndentedString(imagePullSecrets)).append("\n");
    sb.append("    initContainers: ").append(toIndentedString(initContainers)).append("\n");
    sb.append("    nodeName: ").append(toIndentedString(nodeName)).append("\n");
    sb.append("    nodeSelector: ").append(toIndentedString(nodeSelector)).append("\n");
    sb.append("    os: ").append(toIndentedString(os)).append("\n");
    sb.append("    overhead: ").append(toIndentedString(overhead)).append("\n");
    sb.append("    preemptionPolicy: ").append(toIndentedString(preemptionPolicy)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    priorityClassName: ").append(toIndentedString(priorityClassName)).append("\n");
    sb.append("    readinessGates: ").append(toIndentedString(readinessGates)).append("\n");
    sb.append("    restartPolicy: ").append(toIndentedString(restartPolicy)).append("\n");
    sb.append("    runtimeClassName: ").append(toIndentedString(runtimeClassName)).append("\n");
    sb.append("    schedulerName: ").append(toIndentedString(schedulerName)).append("\n");
    sb.append("    securityContext: ").append(toIndentedString(securityContext)).append("\n");
    sb.append("    serviceAccount: ").append(toIndentedString(serviceAccount)).append("\n");
    sb.append("    serviceAccountName: ").append(toIndentedString(serviceAccountName)).append("\n");
    sb.append("    setHostnameAsFQDN: ").append(toIndentedString(setHostnameAsFQDN)).append("\n");
    sb.append("    shareProcessNamespace: ").append(toIndentedString(shareProcessNamespace)).append("\n");
    sb.append("    subdomain: ").append(toIndentedString(subdomain)).append("\n");
    sb.append("    terminationGracePeriodSeconds: ").append(toIndentedString(terminationGracePeriodSeconds)).append("\n");
    sb.append("    tolerations: ").append(toIndentedString(tolerations)).append("\n");
    sb.append("    topologySpreadConstraints: ").append(toIndentedString(topologySpreadConstraints)).append("\n");
    sb.append("    volumes: ").append(toIndentedString(volumes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

