/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.models.V1alpha1RolloutSpecStrategyBlueGreenPostPromotionAnalysis;
import io.argoproj.models.V1alpha1RolloutSpecStrategyCanaryExperiment;
import io.argoproj.models.V1alpha1RolloutSpecStrategyCanaryPause;
import io.argoproj.models.V1alpha1RolloutSpecStrategyCanarySetCanaryScale;
import io.argoproj.models.V1alpha1RolloutSpecStrategyCanarySetHeaderRoute;
import io.argoproj.models.V1alpha1RolloutSpecStrategyCanarySetMirrorRoute;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha1RolloutSpecStrategyCanarySteps
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-19T02:24:32.086Z[Etc/UTC]")
public class V1alpha1RolloutSpecStrategyCanarySteps {
  public static final String SERIALIZED_NAME_ANALYSIS = "analysis";
  @SerializedName(SERIALIZED_NAME_ANALYSIS)
  private V1alpha1RolloutSpecStrategyBlueGreenPostPromotionAnalysis analysis;

  public static final String SERIALIZED_NAME_EXPERIMENT = "experiment";
  @SerializedName(SERIALIZED_NAME_EXPERIMENT)
  private V1alpha1RolloutSpecStrategyCanaryExperiment experiment;

  public static final String SERIALIZED_NAME_PAUSE = "pause";
  @SerializedName(SERIALIZED_NAME_PAUSE)
  private V1alpha1RolloutSpecStrategyCanaryPause pause;

  public static final String SERIALIZED_NAME_SET_CANARY_SCALE = "setCanaryScale";
  @SerializedName(SERIALIZED_NAME_SET_CANARY_SCALE)
  private V1alpha1RolloutSpecStrategyCanarySetCanaryScale setCanaryScale;

  public static final String SERIALIZED_NAME_SET_HEADER_ROUTE = "setHeaderRoute";
  @SerializedName(SERIALIZED_NAME_SET_HEADER_ROUTE)
  private V1alpha1RolloutSpecStrategyCanarySetHeaderRoute setHeaderRoute;

  public static final String SERIALIZED_NAME_SET_MIRROR_ROUTE = "setMirrorRoute";
  @SerializedName(SERIALIZED_NAME_SET_MIRROR_ROUTE)
  private V1alpha1RolloutSpecStrategyCanarySetMirrorRoute setMirrorRoute;

  public static final String SERIALIZED_NAME_SET_WEIGHT = "setWeight";
  @SerializedName(SERIALIZED_NAME_SET_WEIGHT)
  private Integer setWeight;


  public V1alpha1RolloutSpecStrategyCanarySteps analysis(V1alpha1RolloutSpecStrategyBlueGreenPostPromotionAnalysis analysis) {
    
    this.analysis = analysis;
    return this;
  }

   /**
   * Get analysis
   * @return analysis
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1RolloutSpecStrategyBlueGreenPostPromotionAnalysis getAnalysis() {
    return analysis;
  }


  public void setAnalysis(V1alpha1RolloutSpecStrategyBlueGreenPostPromotionAnalysis analysis) {
    this.analysis = analysis;
  }


  public V1alpha1RolloutSpecStrategyCanarySteps experiment(V1alpha1RolloutSpecStrategyCanaryExperiment experiment) {
    
    this.experiment = experiment;
    return this;
  }

   /**
   * Get experiment
   * @return experiment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1RolloutSpecStrategyCanaryExperiment getExperiment() {
    return experiment;
  }


  public void setExperiment(V1alpha1RolloutSpecStrategyCanaryExperiment experiment) {
    this.experiment = experiment;
  }


  public V1alpha1RolloutSpecStrategyCanarySteps pause(V1alpha1RolloutSpecStrategyCanaryPause pause) {
    
    this.pause = pause;
    return this;
  }

   /**
   * Get pause
   * @return pause
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1RolloutSpecStrategyCanaryPause getPause() {
    return pause;
  }


  public void setPause(V1alpha1RolloutSpecStrategyCanaryPause pause) {
    this.pause = pause;
  }


  public V1alpha1RolloutSpecStrategyCanarySteps setCanaryScale(V1alpha1RolloutSpecStrategyCanarySetCanaryScale setCanaryScale) {
    
    this.setCanaryScale = setCanaryScale;
    return this;
  }

   /**
   * Get setCanaryScale
   * @return setCanaryScale
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1RolloutSpecStrategyCanarySetCanaryScale getSetCanaryScale() {
    return setCanaryScale;
  }


  public void setSetCanaryScale(V1alpha1RolloutSpecStrategyCanarySetCanaryScale setCanaryScale) {
    this.setCanaryScale = setCanaryScale;
  }


  public V1alpha1RolloutSpecStrategyCanarySteps setHeaderRoute(V1alpha1RolloutSpecStrategyCanarySetHeaderRoute setHeaderRoute) {
    
    this.setHeaderRoute = setHeaderRoute;
    return this;
  }

   /**
   * Get setHeaderRoute
   * @return setHeaderRoute
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1RolloutSpecStrategyCanarySetHeaderRoute getSetHeaderRoute() {
    return setHeaderRoute;
  }


  public void setSetHeaderRoute(V1alpha1RolloutSpecStrategyCanarySetHeaderRoute setHeaderRoute) {
    this.setHeaderRoute = setHeaderRoute;
  }


  public V1alpha1RolloutSpecStrategyCanarySteps setMirrorRoute(V1alpha1RolloutSpecStrategyCanarySetMirrorRoute setMirrorRoute) {
    
    this.setMirrorRoute = setMirrorRoute;
    return this;
  }

   /**
   * Get setMirrorRoute
   * @return setMirrorRoute
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1RolloutSpecStrategyCanarySetMirrorRoute getSetMirrorRoute() {
    return setMirrorRoute;
  }


  public void setSetMirrorRoute(V1alpha1RolloutSpecStrategyCanarySetMirrorRoute setMirrorRoute) {
    this.setMirrorRoute = setMirrorRoute;
  }


  public V1alpha1RolloutSpecStrategyCanarySteps setWeight(Integer setWeight) {
    
    this.setWeight = setWeight;
    return this;
  }

   /**
   * Get setWeight
   * @return setWeight
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getSetWeight() {
    return setWeight;
  }


  public void setSetWeight(Integer setWeight) {
    this.setWeight = setWeight;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1RolloutSpecStrategyCanarySteps v1alpha1RolloutSpecStrategyCanarySteps = (V1alpha1RolloutSpecStrategyCanarySteps) o;
    return Objects.equals(this.analysis, v1alpha1RolloutSpecStrategyCanarySteps.analysis) &&
        Objects.equals(this.experiment, v1alpha1RolloutSpecStrategyCanarySteps.experiment) &&
        Objects.equals(this.pause, v1alpha1RolloutSpecStrategyCanarySteps.pause) &&
        Objects.equals(this.setCanaryScale, v1alpha1RolloutSpecStrategyCanarySteps.setCanaryScale) &&
        Objects.equals(this.setHeaderRoute, v1alpha1RolloutSpecStrategyCanarySteps.setHeaderRoute) &&
        Objects.equals(this.setMirrorRoute, v1alpha1RolloutSpecStrategyCanarySteps.setMirrorRoute) &&
        Objects.equals(this.setWeight, v1alpha1RolloutSpecStrategyCanarySteps.setWeight);
  }

  @Override
  public int hashCode() {
    return Objects.hash(analysis, experiment, pause, setCanaryScale, setHeaderRoute, setMirrorRoute, setWeight);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1RolloutSpecStrategyCanarySteps {\n");
    sb.append("    analysis: ").append(toIndentedString(analysis)).append("\n");
    sb.append("    experiment: ").append(toIndentedString(experiment)).append("\n");
    sb.append("    pause: ").append(toIndentedString(pause)).append("\n");
    sb.append("    setCanaryScale: ").append(toIndentedString(setCanaryScale)).append("\n");
    sb.append("    setHeaderRoute: ").append(toIndentedString(setHeaderRoute)).append("\n");
    sb.append("    setMirrorRoute: ").append(toIndentedString(setMirrorRoute)).append("\n");
    sb.append("    setWeight: ").append(toIndentedString(setWeight)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

