/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.models.V1alpha1AnalysisTemplateSpecProviderCloudWatchMetricStatMetricDimensions;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha1AnalysisTemplateSpecProviderCloudWatchMetricStatMetric
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-19T02:24:32.086Z[Etc/UTC]")
public class V1alpha1AnalysisTemplateSpecProviderCloudWatchMetricStatMetric {
  public static final String SERIALIZED_NAME_DIMENSIONS = "dimensions";
  @SerializedName(SERIALIZED_NAME_DIMENSIONS)
  private List<V1alpha1AnalysisTemplateSpecProviderCloudWatchMetricStatMetricDimensions> dimensions = null;

  public static final String SERIALIZED_NAME_METRIC_NAME = "metricName";
  @SerializedName(SERIALIZED_NAME_METRIC_NAME)
  private String metricName;

  public static final String SERIALIZED_NAME_NAMESPACE = "namespace";
  @SerializedName(SERIALIZED_NAME_NAMESPACE)
  private String namespace;


  public V1alpha1AnalysisTemplateSpecProviderCloudWatchMetricStatMetric dimensions(List<V1alpha1AnalysisTemplateSpecProviderCloudWatchMetricStatMetricDimensions> dimensions) {
    
    this.dimensions = dimensions;
    return this;
  }

  public V1alpha1AnalysisTemplateSpecProviderCloudWatchMetricStatMetric addDimensionsItem(V1alpha1AnalysisTemplateSpecProviderCloudWatchMetricStatMetricDimensions dimensionsItem) {
    if (this.dimensions == null) {
      this.dimensions = new ArrayList<>();
    }
    this.dimensions.add(dimensionsItem);
    return this;
  }

   /**
   * Get dimensions
   * @return dimensions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1AnalysisTemplateSpecProviderCloudWatchMetricStatMetricDimensions> getDimensions() {
    return dimensions;
  }


  public void setDimensions(List<V1alpha1AnalysisTemplateSpecProviderCloudWatchMetricStatMetricDimensions> dimensions) {
    this.dimensions = dimensions;
  }


  public V1alpha1AnalysisTemplateSpecProviderCloudWatchMetricStatMetric metricName(String metricName) {
    
    this.metricName = metricName;
    return this;
  }

   /**
   * Get metricName
   * @return metricName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMetricName() {
    return metricName;
  }


  public void setMetricName(String metricName) {
    this.metricName = metricName;
  }


  public V1alpha1AnalysisTemplateSpecProviderCloudWatchMetricStatMetric namespace(String namespace) {
    
    this.namespace = namespace;
    return this;
  }

   /**
   * Get namespace
   * @return namespace
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNamespace() {
    return namespace;
  }


  public void setNamespace(String namespace) {
    this.namespace = namespace;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1AnalysisTemplateSpecProviderCloudWatchMetricStatMetric v1alpha1AnalysisTemplateSpecProviderCloudWatchMetricStatMetric = (V1alpha1AnalysisTemplateSpecProviderCloudWatchMetricStatMetric) o;
    return Objects.equals(this.dimensions, v1alpha1AnalysisTemplateSpecProviderCloudWatchMetricStatMetric.dimensions) &&
        Objects.equals(this.metricName, v1alpha1AnalysisTemplateSpecProviderCloudWatchMetricStatMetric.metricName) &&
        Objects.equals(this.namespace, v1alpha1AnalysisTemplateSpecProviderCloudWatchMetricStatMetric.namespace);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dimensions, metricName, namespace);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1AnalysisTemplateSpecProviderCloudWatchMetricStatMetric {\n");
    sb.append("    dimensions: ").append(toIndentedString(dimensions)).append("\n");
    sb.append("    metricName: ").append(toIndentedString(metricName)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

