/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.models.V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioDestinationRule;
import io.argoproj.models.V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualService;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstio
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-19T02:24:32.086Z[Etc/UTC]")
public class V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstio {
  public static final String SERIALIZED_NAME_DESTINATION_RULE = "destinationRule";
  @SerializedName(SERIALIZED_NAME_DESTINATION_RULE)
  private V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioDestinationRule destinationRule;

  public static final String SERIALIZED_NAME_VIRTUAL_SERVICE = "virtualService";
  @SerializedName(SERIALIZED_NAME_VIRTUAL_SERVICE)
  private V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualService virtualService;

  public static final String SERIALIZED_NAME_VIRTUAL_SERVICES = "virtualServices";
  @SerializedName(SERIALIZED_NAME_VIRTUAL_SERVICES)
  private List<V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualService> virtualServices = null;


  public V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstio destinationRule(V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioDestinationRule destinationRule) {
    
    this.destinationRule = destinationRule;
    return this;
  }

   /**
   * Get destinationRule
   * @return destinationRule
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioDestinationRule getDestinationRule() {
    return destinationRule;
  }


  public void setDestinationRule(V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioDestinationRule destinationRule) {
    this.destinationRule = destinationRule;
  }


  public V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstio virtualService(V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualService virtualService) {
    
    this.virtualService = virtualService;
    return this;
  }

   /**
   * Get virtualService
   * @return virtualService
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualService getVirtualService() {
    return virtualService;
  }


  public void setVirtualService(V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualService virtualService) {
    this.virtualService = virtualService;
  }


  public V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstio virtualServices(List<V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualService> virtualServices) {
    
    this.virtualServices = virtualServices;
    return this;
  }

  public V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstio addVirtualServicesItem(V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualService virtualServicesItem) {
    if (this.virtualServices == null) {
      this.virtualServices = new ArrayList<>();
    }
    this.virtualServices.add(virtualServicesItem);
    return this;
  }

   /**
   * Get virtualServices
   * @return virtualServices
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualService> getVirtualServices() {
    return virtualServices;
  }


  public void setVirtualServices(List<V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstioVirtualService> virtualServices) {
    this.virtualServices = virtualServices;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstio v1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstio = (V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstio) o;
    return Objects.equals(this.destinationRule, v1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstio.destinationRule) &&
        Objects.equals(this.virtualService, v1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstio.virtualService) &&
        Objects.equals(this.virtualServices, v1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstio.virtualServices);
  }

  @Override
  public int hashCode() {
    return Objects.hash(destinationRule, virtualService, virtualServices);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1RolloutSpecStrategyCanaryTrafficRoutingIstio {\n");
    sb.append("    destinationRule: ").append(toIndentedString(destinationRule)).append("\n");
    sb.append("    virtualService: ").append(toIndentedString(virtualService)).append("\n");
    sb.append("    virtualServices: ").append(toIndentedString(virtualServices)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

