/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.models.V1alpha1TCPRoute;
import io.argoproj.models.V1alpha1TLSRoute;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * IstioVirtualService holds information on the virtual service the rollout needs to modify
 */
@ApiModel(description = "IstioVirtualService holds information on the virtual service the rollout needs to modify")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-19T21:57:47.017Z[Etc/UTC]")
public class V1alpha1IstioVirtualService {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name = "";

  public static final String SERIALIZED_NAME_ROUTES = "routes";
  @SerializedName(SERIALIZED_NAME_ROUTES)
  private List<String> routes = null;

  public static final String SERIALIZED_NAME_TCP_ROUTES = "tcpRoutes";
  @SerializedName(SERIALIZED_NAME_TCP_ROUTES)
  private List<V1alpha1TCPRoute> tcpRoutes = null;

  public static final String SERIALIZED_NAME_TLS_ROUTES = "tlsRoutes";
  @SerializedName(SERIALIZED_NAME_TLS_ROUTES)
  private List<V1alpha1TLSRoute> tlsRoutes = null;


  public V1alpha1IstioVirtualService name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name holds the name of the VirtualService
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name holds the name of the VirtualService")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1alpha1IstioVirtualService routes(List<String> routes) {
    
    this.routes = routes;
    return this;
  }

  public V1alpha1IstioVirtualService addRoutesItem(String routesItem) {
    if (this.routes == null) {
      this.routes = new ArrayList<>();
    }
    this.routes.add(routesItem);
    return this;
  }

   /**
   * A list of HTTP routes within VirtualService to edit. If omitted, VirtualService must have a single route of this type.
   * @return routes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of HTTP routes within VirtualService to edit. If omitted, VirtualService must have a single route of this type.")

  public List<String> getRoutes() {
    return routes;
  }


  public void setRoutes(List<String> routes) {
    this.routes = routes;
  }


  public V1alpha1IstioVirtualService tcpRoutes(List<V1alpha1TCPRoute> tcpRoutes) {
    
    this.tcpRoutes = tcpRoutes;
    return this;
  }

  public V1alpha1IstioVirtualService addTcpRoutesItem(V1alpha1TCPRoute tcpRoutesItem) {
    if (this.tcpRoutes == null) {
      this.tcpRoutes = new ArrayList<>();
    }
    this.tcpRoutes.add(tcpRoutesItem);
    return this;
  }

   /**
   * A list of TCP routes within VirtualService to edit. If omitted, VirtualService must have a single route of this type.
   * @return tcpRoutes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of TCP routes within VirtualService to edit. If omitted, VirtualService must have a single route of this type.")

  public List<V1alpha1TCPRoute> getTcpRoutes() {
    return tcpRoutes;
  }


  public void setTcpRoutes(List<V1alpha1TCPRoute> tcpRoutes) {
    this.tcpRoutes = tcpRoutes;
  }


  public V1alpha1IstioVirtualService tlsRoutes(List<V1alpha1TLSRoute> tlsRoutes) {
    
    this.tlsRoutes = tlsRoutes;
    return this;
  }

  public V1alpha1IstioVirtualService addTlsRoutesItem(V1alpha1TLSRoute tlsRoutesItem) {
    if (this.tlsRoutes == null) {
      this.tlsRoutes = new ArrayList<>();
    }
    this.tlsRoutes.add(tlsRoutesItem);
    return this;
  }

   /**
   * A list of TLS/HTTPS routes within VirtualService to edit. If omitted, VirtualService must have a single route of this type.
   * @return tlsRoutes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of TLS/HTTPS routes within VirtualService to edit. If omitted, VirtualService must have a single route of this type.")

  public List<V1alpha1TLSRoute> getTlsRoutes() {
    return tlsRoutes;
  }


  public void setTlsRoutes(List<V1alpha1TLSRoute> tlsRoutes) {
    this.tlsRoutes = tlsRoutes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1IstioVirtualService v1alpha1IstioVirtualService = (V1alpha1IstioVirtualService) o;
    return Objects.equals(this.name, v1alpha1IstioVirtualService.name) &&
        Objects.equals(this.routes, v1alpha1IstioVirtualService.routes) &&
        Objects.equals(this.tcpRoutes, v1alpha1IstioVirtualService.tcpRoutes) &&
        Objects.equals(this.tlsRoutes, v1alpha1IstioVirtualService.tlsRoutes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, routes, tcpRoutes, tlsRoutes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1IstioVirtualService {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    routes: ").append(toIndentedString(routes)).append("\n");
    sb.append("    tcpRoutes: ").append(toIndentedString(tcpRoutes)).append("\n");
    sb.append("    tlsRoutes: ").append(toIndentedString(tlsRoutes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

