/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.models.V1alpha1AnalysisTemplateSpecProviderJobMetadata;
import io.argoproj.models.V1alpha1RolloutSpecStrategyBlueGreenAntiAffinity;
import io.argoproj.models.V1alpha1RolloutSpecStrategyBlueGreenPostPromotionAnalysis;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha1RolloutSpecStrategyBlueGreen
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-19T02:24:32.086Z[Etc/UTC]")
public class V1alpha1RolloutSpecStrategyBlueGreen {
  public static final String SERIALIZED_NAME_ABORT_SCALE_DOWN_DELAY_SECONDS = "abortScaleDownDelaySeconds";
  @SerializedName(SERIALIZED_NAME_ABORT_SCALE_DOWN_DELAY_SECONDS)
  private Integer abortScaleDownDelaySeconds;

  public static final String SERIALIZED_NAME_ACTIVE_METADATA = "activeMetadata";
  @SerializedName(SERIALIZED_NAME_ACTIVE_METADATA)
  private V1alpha1AnalysisTemplateSpecProviderJobMetadata activeMetadata;

  public static final String SERIALIZED_NAME_ACTIVE_SERVICE = "activeService";
  @SerializedName(SERIALIZED_NAME_ACTIVE_SERVICE)
  private String activeService;

  public static final String SERIALIZED_NAME_ANTI_AFFINITY = "antiAffinity";
  @SerializedName(SERIALIZED_NAME_ANTI_AFFINITY)
  private V1alpha1RolloutSpecStrategyBlueGreenAntiAffinity antiAffinity;

  public static final String SERIALIZED_NAME_AUTO_PROMOTION_ENABLED = "autoPromotionEnabled";
  @SerializedName(SERIALIZED_NAME_AUTO_PROMOTION_ENABLED)
  private Boolean autoPromotionEnabled;

  public static final String SERIALIZED_NAME_AUTO_PROMOTION_SECONDS = "autoPromotionSeconds";
  @SerializedName(SERIALIZED_NAME_AUTO_PROMOTION_SECONDS)
  private Integer autoPromotionSeconds;

  public static final String SERIALIZED_NAME_MAX_UNAVAILABLE = "maxUnavailable";
  @SerializedName(SERIALIZED_NAME_MAX_UNAVAILABLE)
  private Object maxUnavailable;

  public static final String SERIALIZED_NAME_POST_PROMOTION_ANALYSIS = "postPromotionAnalysis";
  @SerializedName(SERIALIZED_NAME_POST_PROMOTION_ANALYSIS)
  private V1alpha1RolloutSpecStrategyBlueGreenPostPromotionAnalysis postPromotionAnalysis;

  public static final String SERIALIZED_NAME_PRE_PROMOTION_ANALYSIS = "prePromotionAnalysis";
  @SerializedName(SERIALIZED_NAME_PRE_PROMOTION_ANALYSIS)
  private V1alpha1RolloutSpecStrategyBlueGreenPostPromotionAnalysis prePromotionAnalysis;

  public static final String SERIALIZED_NAME_PREVIEW_METADATA = "previewMetadata";
  @SerializedName(SERIALIZED_NAME_PREVIEW_METADATA)
  private V1alpha1AnalysisTemplateSpecProviderJobMetadata previewMetadata;

  public static final String SERIALIZED_NAME_PREVIEW_REPLICA_COUNT = "previewReplicaCount";
  @SerializedName(SERIALIZED_NAME_PREVIEW_REPLICA_COUNT)
  private Integer previewReplicaCount;

  public static final String SERIALIZED_NAME_PREVIEW_SERVICE = "previewService";
  @SerializedName(SERIALIZED_NAME_PREVIEW_SERVICE)
  private String previewService;

  public static final String SERIALIZED_NAME_SCALE_DOWN_DELAY_REVISION_LIMIT = "scaleDownDelayRevisionLimit";
  @SerializedName(SERIALIZED_NAME_SCALE_DOWN_DELAY_REVISION_LIMIT)
  private Integer scaleDownDelayRevisionLimit;

  public static final String SERIALIZED_NAME_SCALE_DOWN_DELAY_SECONDS = "scaleDownDelaySeconds";
  @SerializedName(SERIALIZED_NAME_SCALE_DOWN_DELAY_SECONDS)
  private Integer scaleDownDelaySeconds;


  public V1alpha1RolloutSpecStrategyBlueGreen abortScaleDownDelaySeconds(Integer abortScaleDownDelaySeconds) {
    
    this.abortScaleDownDelaySeconds = abortScaleDownDelaySeconds;
    return this;
  }

   /**
   * Get abortScaleDownDelaySeconds
   * @return abortScaleDownDelaySeconds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getAbortScaleDownDelaySeconds() {
    return abortScaleDownDelaySeconds;
  }


  public void setAbortScaleDownDelaySeconds(Integer abortScaleDownDelaySeconds) {
    this.abortScaleDownDelaySeconds = abortScaleDownDelaySeconds;
  }


  public V1alpha1RolloutSpecStrategyBlueGreen activeMetadata(V1alpha1AnalysisTemplateSpecProviderJobMetadata activeMetadata) {
    
    this.activeMetadata = activeMetadata;
    return this;
  }

   /**
   * Get activeMetadata
   * @return activeMetadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1AnalysisTemplateSpecProviderJobMetadata getActiveMetadata() {
    return activeMetadata;
  }


  public void setActiveMetadata(V1alpha1AnalysisTemplateSpecProviderJobMetadata activeMetadata) {
    this.activeMetadata = activeMetadata;
  }


  public V1alpha1RolloutSpecStrategyBlueGreen activeService(String activeService) {
    
    this.activeService = activeService;
    return this;
  }

   /**
   * Get activeService
   * @return activeService
  **/
  @ApiModelProperty(required = true, value = "")

  public String getActiveService() {
    return activeService;
  }


  public void setActiveService(String activeService) {
    this.activeService = activeService;
  }


  public V1alpha1RolloutSpecStrategyBlueGreen antiAffinity(V1alpha1RolloutSpecStrategyBlueGreenAntiAffinity antiAffinity) {
    
    this.antiAffinity = antiAffinity;
    return this;
  }

   /**
   * Get antiAffinity
   * @return antiAffinity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1RolloutSpecStrategyBlueGreenAntiAffinity getAntiAffinity() {
    return antiAffinity;
  }


  public void setAntiAffinity(V1alpha1RolloutSpecStrategyBlueGreenAntiAffinity antiAffinity) {
    this.antiAffinity = antiAffinity;
  }


  public V1alpha1RolloutSpecStrategyBlueGreen autoPromotionEnabled(Boolean autoPromotionEnabled) {
    
    this.autoPromotionEnabled = autoPromotionEnabled;
    return this;
  }

   /**
   * Get autoPromotionEnabled
   * @return autoPromotionEnabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getAutoPromotionEnabled() {
    return autoPromotionEnabled;
  }


  public void setAutoPromotionEnabled(Boolean autoPromotionEnabled) {
    this.autoPromotionEnabled = autoPromotionEnabled;
  }


  public V1alpha1RolloutSpecStrategyBlueGreen autoPromotionSeconds(Integer autoPromotionSeconds) {
    
    this.autoPromotionSeconds = autoPromotionSeconds;
    return this;
  }

   /**
   * Get autoPromotionSeconds
   * @return autoPromotionSeconds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getAutoPromotionSeconds() {
    return autoPromotionSeconds;
  }


  public void setAutoPromotionSeconds(Integer autoPromotionSeconds) {
    this.autoPromotionSeconds = autoPromotionSeconds;
  }


  public V1alpha1RolloutSpecStrategyBlueGreen maxUnavailable(Object maxUnavailable) {
    
    this.maxUnavailable = maxUnavailable;
    return this;
  }

   /**
   * Get maxUnavailable
   * @return maxUnavailable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getMaxUnavailable() {
    return maxUnavailable;
  }


  public void setMaxUnavailable(Object maxUnavailable) {
    this.maxUnavailable = maxUnavailable;
  }


  public V1alpha1RolloutSpecStrategyBlueGreen postPromotionAnalysis(V1alpha1RolloutSpecStrategyBlueGreenPostPromotionAnalysis postPromotionAnalysis) {
    
    this.postPromotionAnalysis = postPromotionAnalysis;
    return this;
  }

   /**
   * Get postPromotionAnalysis
   * @return postPromotionAnalysis
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1RolloutSpecStrategyBlueGreenPostPromotionAnalysis getPostPromotionAnalysis() {
    return postPromotionAnalysis;
  }


  public void setPostPromotionAnalysis(V1alpha1RolloutSpecStrategyBlueGreenPostPromotionAnalysis postPromotionAnalysis) {
    this.postPromotionAnalysis = postPromotionAnalysis;
  }


  public V1alpha1RolloutSpecStrategyBlueGreen prePromotionAnalysis(V1alpha1RolloutSpecStrategyBlueGreenPostPromotionAnalysis prePromotionAnalysis) {
    
    this.prePromotionAnalysis = prePromotionAnalysis;
    return this;
  }

   /**
   * Get prePromotionAnalysis
   * @return prePromotionAnalysis
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1RolloutSpecStrategyBlueGreenPostPromotionAnalysis getPrePromotionAnalysis() {
    return prePromotionAnalysis;
  }


  public void setPrePromotionAnalysis(V1alpha1RolloutSpecStrategyBlueGreenPostPromotionAnalysis prePromotionAnalysis) {
    this.prePromotionAnalysis = prePromotionAnalysis;
  }


  public V1alpha1RolloutSpecStrategyBlueGreen previewMetadata(V1alpha1AnalysisTemplateSpecProviderJobMetadata previewMetadata) {
    
    this.previewMetadata = previewMetadata;
    return this;
  }

   /**
   * Get previewMetadata
   * @return previewMetadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1AnalysisTemplateSpecProviderJobMetadata getPreviewMetadata() {
    return previewMetadata;
  }


  public void setPreviewMetadata(V1alpha1AnalysisTemplateSpecProviderJobMetadata previewMetadata) {
    this.previewMetadata = previewMetadata;
  }


  public V1alpha1RolloutSpecStrategyBlueGreen previewReplicaCount(Integer previewReplicaCount) {
    
    this.previewReplicaCount = previewReplicaCount;
    return this;
  }

   /**
   * Get previewReplicaCount
   * @return previewReplicaCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getPreviewReplicaCount() {
    return previewReplicaCount;
  }


  public void setPreviewReplicaCount(Integer previewReplicaCount) {
    this.previewReplicaCount = previewReplicaCount;
  }


  public V1alpha1RolloutSpecStrategyBlueGreen previewService(String previewService) {
    
    this.previewService = previewService;
    return this;
  }

   /**
   * Get previewService
   * @return previewService
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPreviewService() {
    return previewService;
  }


  public void setPreviewService(String previewService) {
    this.previewService = previewService;
  }


  public V1alpha1RolloutSpecStrategyBlueGreen scaleDownDelayRevisionLimit(Integer scaleDownDelayRevisionLimit) {
    
    this.scaleDownDelayRevisionLimit = scaleDownDelayRevisionLimit;
    return this;
  }

   /**
   * Get scaleDownDelayRevisionLimit
   * @return scaleDownDelayRevisionLimit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getScaleDownDelayRevisionLimit() {
    return scaleDownDelayRevisionLimit;
  }


  public void setScaleDownDelayRevisionLimit(Integer scaleDownDelayRevisionLimit) {
    this.scaleDownDelayRevisionLimit = scaleDownDelayRevisionLimit;
  }


  public V1alpha1RolloutSpecStrategyBlueGreen scaleDownDelaySeconds(Integer scaleDownDelaySeconds) {
    
    this.scaleDownDelaySeconds = scaleDownDelaySeconds;
    return this;
  }

   /**
   * Get scaleDownDelaySeconds
   * @return scaleDownDelaySeconds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getScaleDownDelaySeconds() {
    return scaleDownDelaySeconds;
  }


  public void setScaleDownDelaySeconds(Integer scaleDownDelaySeconds) {
    this.scaleDownDelaySeconds = scaleDownDelaySeconds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1RolloutSpecStrategyBlueGreen v1alpha1RolloutSpecStrategyBlueGreen = (V1alpha1RolloutSpecStrategyBlueGreen) o;
    return Objects.equals(this.abortScaleDownDelaySeconds, v1alpha1RolloutSpecStrategyBlueGreen.abortScaleDownDelaySeconds) &&
        Objects.equals(this.activeMetadata, v1alpha1RolloutSpecStrategyBlueGreen.activeMetadata) &&
        Objects.equals(this.activeService, v1alpha1RolloutSpecStrategyBlueGreen.activeService) &&
        Objects.equals(this.antiAffinity, v1alpha1RolloutSpecStrategyBlueGreen.antiAffinity) &&
        Objects.equals(this.autoPromotionEnabled, v1alpha1RolloutSpecStrategyBlueGreen.autoPromotionEnabled) &&
        Objects.equals(this.autoPromotionSeconds, v1alpha1RolloutSpecStrategyBlueGreen.autoPromotionSeconds) &&
        Objects.equals(this.maxUnavailable, v1alpha1RolloutSpecStrategyBlueGreen.maxUnavailable) &&
        Objects.equals(this.postPromotionAnalysis, v1alpha1RolloutSpecStrategyBlueGreen.postPromotionAnalysis) &&
        Objects.equals(this.prePromotionAnalysis, v1alpha1RolloutSpecStrategyBlueGreen.prePromotionAnalysis) &&
        Objects.equals(this.previewMetadata, v1alpha1RolloutSpecStrategyBlueGreen.previewMetadata) &&
        Objects.equals(this.previewReplicaCount, v1alpha1RolloutSpecStrategyBlueGreen.previewReplicaCount) &&
        Objects.equals(this.previewService, v1alpha1RolloutSpecStrategyBlueGreen.previewService) &&
        Objects.equals(this.scaleDownDelayRevisionLimit, v1alpha1RolloutSpecStrategyBlueGreen.scaleDownDelayRevisionLimit) &&
        Objects.equals(this.scaleDownDelaySeconds, v1alpha1RolloutSpecStrategyBlueGreen.scaleDownDelaySeconds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(abortScaleDownDelaySeconds, activeMetadata, activeService, antiAffinity, autoPromotionEnabled, autoPromotionSeconds, maxUnavailable, postPromotionAnalysis, prePromotionAnalysis, previewMetadata, previewReplicaCount, previewService, scaleDownDelayRevisionLimit, scaleDownDelaySeconds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1RolloutSpecStrategyBlueGreen {\n");
    sb.append("    abortScaleDownDelaySeconds: ").append(toIndentedString(abortScaleDownDelaySeconds)).append("\n");
    sb.append("    activeMetadata: ").append(toIndentedString(activeMetadata)).append("\n");
    sb.append("    activeService: ").append(toIndentedString(activeService)).append("\n");
    sb.append("    antiAffinity: ").append(toIndentedString(antiAffinity)).append("\n");
    sb.append("    autoPromotionEnabled: ").append(toIndentedString(autoPromotionEnabled)).append("\n");
    sb.append("    autoPromotionSeconds: ").append(toIndentedString(autoPromotionSeconds)).append("\n");
    sb.append("    maxUnavailable: ").append(toIndentedString(maxUnavailable)).append("\n");
    sb.append("    postPromotionAnalysis: ").append(toIndentedString(postPromotionAnalysis)).append("\n");
    sb.append("    prePromotionAnalysis: ").append(toIndentedString(prePromotionAnalysis)).append("\n");
    sb.append("    previewMetadata: ").append(toIndentedString(previewMetadata)).append("\n");
    sb.append("    previewReplicaCount: ").append(toIndentedString(previewReplicaCount)).append("\n");
    sb.append("    previewService: ").append(toIndentedString(previewService)).append("\n");
    sb.append("    scaleDownDelayRevisionLimit: ").append(toIndentedString(scaleDownDelayRevisionLimit)).append("\n");
    sb.append("    scaleDownDelaySeconds: ").append(toIndentedString(scaleDownDelaySeconds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

