/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.models.V1alpha1RolloutAnalysisRunStatus;
import io.argoproj.models.V1alpha1TrafficWeights;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CanaryStatus status fields that only pertain to the canary rollout
 */
@ApiModel(description = "CanaryStatus status fields that only pertain to the canary rollout")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-19T21:57:47.017Z[Etc/UTC]")
public class V1alpha1CanaryStatus {
  public static final String SERIALIZED_NAME_CURRENT_BACKGROUND_ANALYSIS_RUN_STATUS = "currentBackgroundAnalysisRunStatus";
  @SerializedName(SERIALIZED_NAME_CURRENT_BACKGROUND_ANALYSIS_RUN_STATUS)
  private V1alpha1RolloutAnalysisRunStatus currentBackgroundAnalysisRunStatus;

  public static final String SERIALIZED_NAME_CURRENT_EXPERIMENT = "currentExperiment";
  @SerializedName(SERIALIZED_NAME_CURRENT_EXPERIMENT)
  private String currentExperiment;

  public static final String SERIALIZED_NAME_CURRENT_STEP_ANALYSIS_RUN_STATUS = "currentStepAnalysisRunStatus";
  @SerializedName(SERIALIZED_NAME_CURRENT_STEP_ANALYSIS_RUN_STATUS)
  private V1alpha1RolloutAnalysisRunStatus currentStepAnalysisRunStatus;

  public static final String SERIALIZED_NAME_STABLE_PING_PONG = "stablePingPong";
  @SerializedName(SERIALIZED_NAME_STABLE_PING_PONG)
  private String stablePingPong;

  public static final String SERIALIZED_NAME_WEIGHTS = "weights";
  @SerializedName(SERIALIZED_NAME_WEIGHTS)
  private V1alpha1TrafficWeights weights;


  public V1alpha1CanaryStatus currentBackgroundAnalysisRunStatus(V1alpha1RolloutAnalysisRunStatus currentBackgroundAnalysisRunStatus) {
    
    this.currentBackgroundAnalysisRunStatus = currentBackgroundAnalysisRunStatus;
    return this;
  }

   /**
   * Get currentBackgroundAnalysisRunStatus
   * @return currentBackgroundAnalysisRunStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1RolloutAnalysisRunStatus getCurrentBackgroundAnalysisRunStatus() {
    return currentBackgroundAnalysisRunStatus;
  }


  public void setCurrentBackgroundAnalysisRunStatus(V1alpha1RolloutAnalysisRunStatus currentBackgroundAnalysisRunStatus) {
    this.currentBackgroundAnalysisRunStatus = currentBackgroundAnalysisRunStatus;
  }


  public V1alpha1CanaryStatus currentExperiment(String currentExperiment) {
    
    this.currentExperiment = currentExperiment;
    return this;
  }

   /**
   * CurrentExperiment indicates the running experiment
   * @return currentExperiment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "CurrentExperiment indicates the running experiment")

  public String getCurrentExperiment() {
    return currentExperiment;
  }


  public void setCurrentExperiment(String currentExperiment) {
    this.currentExperiment = currentExperiment;
  }


  public V1alpha1CanaryStatus currentStepAnalysisRunStatus(V1alpha1RolloutAnalysisRunStatus currentStepAnalysisRunStatus) {
    
    this.currentStepAnalysisRunStatus = currentStepAnalysisRunStatus;
    return this;
  }

   /**
   * Get currentStepAnalysisRunStatus
   * @return currentStepAnalysisRunStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1RolloutAnalysisRunStatus getCurrentStepAnalysisRunStatus() {
    return currentStepAnalysisRunStatus;
  }


  public void setCurrentStepAnalysisRunStatus(V1alpha1RolloutAnalysisRunStatus currentStepAnalysisRunStatus) {
    this.currentStepAnalysisRunStatus = currentStepAnalysisRunStatus;
  }


  public V1alpha1CanaryStatus stablePingPong(String stablePingPong) {
    
    this.stablePingPong = stablePingPong;
    return this;
  }

   /**
   * StablePingPong For the ping-pong feature holds the current stable service, ping or pong
   * @return stablePingPong
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "StablePingPong For the ping-pong feature holds the current stable service, ping or pong")

  public String getStablePingPong() {
    return stablePingPong;
  }


  public void setStablePingPong(String stablePingPong) {
    this.stablePingPong = stablePingPong;
  }


  public V1alpha1CanaryStatus weights(V1alpha1TrafficWeights weights) {
    
    this.weights = weights;
    return this;
  }

   /**
   * Get weights
   * @return weights
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1TrafficWeights getWeights() {
    return weights;
  }


  public void setWeights(V1alpha1TrafficWeights weights) {
    this.weights = weights;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1CanaryStatus v1alpha1CanaryStatus = (V1alpha1CanaryStatus) o;
    return Objects.equals(this.currentBackgroundAnalysisRunStatus, v1alpha1CanaryStatus.currentBackgroundAnalysisRunStatus) &&
        Objects.equals(this.currentExperiment, v1alpha1CanaryStatus.currentExperiment) &&
        Objects.equals(this.currentStepAnalysisRunStatus, v1alpha1CanaryStatus.currentStepAnalysisRunStatus) &&
        Objects.equals(this.stablePingPong, v1alpha1CanaryStatus.stablePingPong) &&
        Objects.equals(this.weights, v1alpha1CanaryStatus.weights);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currentBackgroundAnalysisRunStatus, currentExperiment, currentStepAnalysisRunStatus, stablePingPong, weights);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1CanaryStatus {\n");
    sb.append("    currentBackgroundAnalysisRunStatus: ").append(toIndentedString(currentBackgroundAnalysisRunStatus)).append("\n");
    sb.append("    currentExperiment: ").append(toIndentedString(currentExperiment)).append("\n");
    sb.append("    currentStepAnalysisRunStatus: ").append(toIndentedString(currentStepAnalysisRunStatus)).append("\n");
    sb.append("    stablePingPong: ").append(toIndentedString(stablePingPong)).append("\n");
    sb.append("    weights: ").append(toIndentedString(weights)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

