/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.models.IoK8sApimachineryPkgUtilIntstrIntOrString;
import io.argoproj.models.V1alpha1AntiAffinity;
import io.argoproj.models.V1alpha1PodTemplateMetadata;
import io.argoproj.models.V1alpha1RolloutAnalysis;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BlueGreenStrategy defines parameters for Blue Green deployment
 */
@ApiModel(description = "BlueGreenStrategy defines parameters for Blue Green deployment")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-19T21:57:47.017Z[Etc/UTC]")
public class V1alpha1BlueGreenStrategy {
  public static final String SERIALIZED_NAME_ABORT_SCALE_DOWN_DELAY_SECONDS = "abortScaleDownDelaySeconds";
  @SerializedName(SERIALIZED_NAME_ABORT_SCALE_DOWN_DELAY_SECONDS)
  private Integer abortScaleDownDelaySeconds;

  public static final String SERIALIZED_NAME_ACTIVE_METADATA = "activeMetadata";
  @SerializedName(SERIALIZED_NAME_ACTIVE_METADATA)
  private V1alpha1PodTemplateMetadata activeMetadata;

  public static final String SERIALIZED_NAME_ACTIVE_SERVICE = "activeService";
  @SerializedName(SERIALIZED_NAME_ACTIVE_SERVICE)
  private String activeService = "";

  public static final String SERIALIZED_NAME_ANTI_AFFINITY = "antiAffinity";
  @SerializedName(SERIALIZED_NAME_ANTI_AFFINITY)
  private V1alpha1AntiAffinity antiAffinity;

  public static final String SERIALIZED_NAME_AUTO_PROMOTION_ENABLED = "autoPromotionEnabled";
  @SerializedName(SERIALIZED_NAME_AUTO_PROMOTION_ENABLED)
  private Boolean autoPromotionEnabled;

  public static final String SERIALIZED_NAME_AUTO_PROMOTION_SECONDS = "autoPromotionSeconds";
  @SerializedName(SERIALIZED_NAME_AUTO_PROMOTION_SECONDS)
  private Integer autoPromotionSeconds;

  public static final String SERIALIZED_NAME_MAX_UNAVAILABLE = "maxUnavailable";
  @SerializedName(SERIALIZED_NAME_MAX_UNAVAILABLE)
  private IoK8sApimachineryPkgUtilIntstrIntOrString maxUnavailable = null;

  public static final String SERIALIZED_NAME_POST_PROMOTION_ANALYSIS = "postPromotionAnalysis";
  @SerializedName(SERIALIZED_NAME_POST_PROMOTION_ANALYSIS)
  private V1alpha1RolloutAnalysis postPromotionAnalysis;

  public static final String SERIALIZED_NAME_PRE_PROMOTION_ANALYSIS = "prePromotionAnalysis";
  @SerializedName(SERIALIZED_NAME_PRE_PROMOTION_ANALYSIS)
  private V1alpha1RolloutAnalysis prePromotionAnalysis;

  public static final String SERIALIZED_NAME_PREVIEW_METADATA = "previewMetadata";
  @SerializedName(SERIALIZED_NAME_PREVIEW_METADATA)
  private V1alpha1PodTemplateMetadata previewMetadata;

  public static final String SERIALIZED_NAME_PREVIEW_REPLICA_COUNT = "previewReplicaCount";
  @SerializedName(SERIALIZED_NAME_PREVIEW_REPLICA_COUNT)
  private Integer previewReplicaCount;

  public static final String SERIALIZED_NAME_PREVIEW_SERVICE = "previewService";
  @SerializedName(SERIALIZED_NAME_PREVIEW_SERVICE)
  private String previewService;

  public static final String SERIALIZED_NAME_SCALE_DOWN_DELAY_REVISION_LIMIT = "scaleDownDelayRevisionLimit";
  @SerializedName(SERIALIZED_NAME_SCALE_DOWN_DELAY_REVISION_LIMIT)
  private Integer scaleDownDelayRevisionLimit;

  public static final String SERIALIZED_NAME_SCALE_DOWN_DELAY_SECONDS = "scaleDownDelaySeconds";
  @SerializedName(SERIALIZED_NAME_SCALE_DOWN_DELAY_SECONDS)
  private Integer scaleDownDelaySeconds;


  public V1alpha1BlueGreenStrategy abortScaleDownDelaySeconds(Integer abortScaleDownDelaySeconds) {
    
    this.abortScaleDownDelaySeconds = abortScaleDownDelaySeconds;
    return this;
  }

   /**
   * AbortScaleDownDelaySeconds adds a delay in second before scaling down the preview replicaset if update is aborted. 0 means not to scale down. Default is 30 second
   * @return abortScaleDownDelaySeconds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "AbortScaleDownDelaySeconds adds a delay in second before scaling down the preview replicaset if update is aborted. 0 means not to scale down. Default is 30 second")

  public Integer getAbortScaleDownDelaySeconds() {
    return abortScaleDownDelaySeconds;
  }


  public void setAbortScaleDownDelaySeconds(Integer abortScaleDownDelaySeconds) {
    this.abortScaleDownDelaySeconds = abortScaleDownDelaySeconds;
  }


  public V1alpha1BlueGreenStrategy activeMetadata(V1alpha1PodTemplateMetadata activeMetadata) {
    
    this.activeMetadata = activeMetadata;
    return this;
  }

   /**
   * Get activeMetadata
   * @return activeMetadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1PodTemplateMetadata getActiveMetadata() {
    return activeMetadata;
  }


  public void setActiveMetadata(V1alpha1PodTemplateMetadata activeMetadata) {
    this.activeMetadata = activeMetadata;
  }


  public V1alpha1BlueGreenStrategy activeService(String activeService) {
    
    this.activeService = activeService;
    return this;
  }

   /**
   * Name of the service that the rollout modifies as the active service.
   * @return activeService
  **/
  @ApiModelProperty(required = true, value = "Name of the service that the rollout modifies as the active service.")

  public String getActiveService() {
    return activeService;
  }


  public void setActiveService(String activeService) {
    this.activeService = activeService;
  }


  public V1alpha1BlueGreenStrategy antiAffinity(V1alpha1AntiAffinity antiAffinity) {
    
    this.antiAffinity = antiAffinity;
    return this;
  }

   /**
   * Get antiAffinity
   * @return antiAffinity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1AntiAffinity getAntiAffinity() {
    return antiAffinity;
  }


  public void setAntiAffinity(V1alpha1AntiAffinity antiAffinity) {
    this.antiAffinity = antiAffinity;
  }


  public V1alpha1BlueGreenStrategy autoPromotionEnabled(Boolean autoPromotionEnabled) {
    
    this.autoPromotionEnabled = autoPromotionEnabled;
    return this;
  }

   /**
   * AutoPromotionEnabled indicates if the rollout should automatically promote the new ReplicaSet to the active service or enter a paused state. If not specified, the default value is true.
   * @return autoPromotionEnabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "AutoPromotionEnabled indicates if the rollout should automatically promote the new ReplicaSet to the active service or enter a paused state. If not specified, the default value is true.")

  public Boolean getAutoPromotionEnabled() {
    return autoPromotionEnabled;
  }


  public void setAutoPromotionEnabled(Boolean autoPromotionEnabled) {
    this.autoPromotionEnabled = autoPromotionEnabled;
  }


  public V1alpha1BlueGreenStrategy autoPromotionSeconds(Integer autoPromotionSeconds) {
    
    this.autoPromotionSeconds = autoPromotionSeconds;
    return this;
  }

   /**
   * AutoPromotionSeconds is a duration in seconds in which to delay auto-promotion (default: 0). The countdown begins after the preview ReplicaSet have reached full availability. This option is ignored if autoPromotionEnabled is set to false.
   * @return autoPromotionSeconds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "AutoPromotionSeconds is a duration in seconds in which to delay auto-promotion (default: 0). The countdown begins after the preview ReplicaSet have reached full availability. This option is ignored if autoPromotionEnabled is set to false.")

  public Integer getAutoPromotionSeconds() {
    return autoPromotionSeconds;
  }


  public void setAutoPromotionSeconds(Integer autoPromotionSeconds) {
    this.autoPromotionSeconds = autoPromotionSeconds;
  }


  public V1alpha1BlueGreenStrategy maxUnavailable(IoK8sApimachineryPkgUtilIntstrIntOrString maxUnavailable) {
    
    this.maxUnavailable = maxUnavailable;
    return this;
  }

   /**
   * Get maxUnavailable
   * @return maxUnavailable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public IoK8sApimachineryPkgUtilIntstrIntOrString getMaxUnavailable() {
    return maxUnavailable;
  }


  public void setMaxUnavailable(IoK8sApimachineryPkgUtilIntstrIntOrString maxUnavailable) {
    this.maxUnavailable = maxUnavailable;
  }


  public V1alpha1BlueGreenStrategy postPromotionAnalysis(V1alpha1RolloutAnalysis postPromotionAnalysis) {
    
    this.postPromotionAnalysis = postPromotionAnalysis;
    return this;
  }

   /**
   * Get postPromotionAnalysis
   * @return postPromotionAnalysis
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1RolloutAnalysis getPostPromotionAnalysis() {
    return postPromotionAnalysis;
  }


  public void setPostPromotionAnalysis(V1alpha1RolloutAnalysis postPromotionAnalysis) {
    this.postPromotionAnalysis = postPromotionAnalysis;
  }


  public V1alpha1BlueGreenStrategy prePromotionAnalysis(V1alpha1RolloutAnalysis prePromotionAnalysis) {
    
    this.prePromotionAnalysis = prePromotionAnalysis;
    return this;
  }

   /**
   * Get prePromotionAnalysis
   * @return prePromotionAnalysis
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1RolloutAnalysis getPrePromotionAnalysis() {
    return prePromotionAnalysis;
  }


  public void setPrePromotionAnalysis(V1alpha1RolloutAnalysis prePromotionAnalysis) {
    this.prePromotionAnalysis = prePromotionAnalysis;
  }


  public V1alpha1BlueGreenStrategy previewMetadata(V1alpha1PodTemplateMetadata previewMetadata) {
    
    this.previewMetadata = previewMetadata;
    return this;
  }

   /**
   * Get previewMetadata
   * @return previewMetadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1PodTemplateMetadata getPreviewMetadata() {
    return previewMetadata;
  }


  public void setPreviewMetadata(V1alpha1PodTemplateMetadata previewMetadata) {
    this.previewMetadata = previewMetadata;
  }


  public V1alpha1BlueGreenStrategy previewReplicaCount(Integer previewReplicaCount) {
    
    this.previewReplicaCount = previewReplicaCount;
    return this;
  }

   /**
   * PreviewReplicaCount is the number of replicas to run for the preview stack before the switchover. Once the rollout is resumed the desired replicaset will be full scaled up before the switch occurs
   * @return previewReplicaCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "PreviewReplicaCount is the number of replicas to run for the preview stack before the switchover. Once the rollout is resumed the desired replicaset will be full scaled up before the switch occurs")

  public Integer getPreviewReplicaCount() {
    return previewReplicaCount;
  }


  public void setPreviewReplicaCount(Integer previewReplicaCount) {
    this.previewReplicaCount = previewReplicaCount;
  }


  public V1alpha1BlueGreenStrategy previewService(String previewService) {
    
    this.previewService = previewService;
    return this;
  }

   /**
   * Name of the service that the rollout modifies as the preview service.
   * @return previewService
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name of the service that the rollout modifies as the preview service.")

  public String getPreviewService() {
    return previewService;
  }


  public void setPreviewService(String previewService) {
    this.previewService = previewService;
  }


  public V1alpha1BlueGreenStrategy scaleDownDelayRevisionLimit(Integer scaleDownDelayRevisionLimit) {
    
    this.scaleDownDelayRevisionLimit = scaleDownDelayRevisionLimit;
    return this;
  }

   /**
   * ScaleDownDelayRevisionLimit limits the number of old RS that can run at one time before getting scaled down
   * @return scaleDownDelayRevisionLimit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ScaleDownDelayRevisionLimit limits the number of old RS that can run at one time before getting scaled down")

  public Integer getScaleDownDelayRevisionLimit() {
    return scaleDownDelayRevisionLimit;
  }


  public void setScaleDownDelayRevisionLimit(Integer scaleDownDelayRevisionLimit) {
    this.scaleDownDelayRevisionLimit = scaleDownDelayRevisionLimit;
  }


  public V1alpha1BlueGreenStrategy scaleDownDelaySeconds(Integer scaleDownDelaySeconds) {
    
    this.scaleDownDelaySeconds = scaleDownDelaySeconds;
    return this;
  }

   /**
   * ScaleDownDelaySeconds adds a delay before scaling down the previous replicaset. If omitted, the Rollout waits 30 seconds before scaling down the previous ReplicaSet. A minimum of 30 seconds is recommended to ensure IP table propagation across the nodes in a cluster. See https://github.com/argoproj/argo-rollouts/issues/19#issuecomment-476329960 for more information
   * @return scaleDownDelaySeconds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ScaleDownDelaySeconds adds a delay before scaling down the previous replicaset. If omitted, the Rollout waits 30 seconds before scaling down the previous ReplicaSet. A minimum of 30 seconds is recommended to ensure IP table propagation across the nodes in a cluster. See https://github.com/argoproj/argo-rollouts/issues/19#issuecomment-476329960 for more information")

  public Integer getScaleDownDelaySeconds() {
    return scaleDownDelaySeconds;
  }


  public void setScaleDownDelaySeconds(Integer scaleDownDelaySeconds) {
    this.scaleDownDelaySeconds = scaleDownDelaySeconds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1BlueGreenStrategy v1alpha1BlueGreenStrategy = (V1alpha1BlueGreenStrategy) o;
    return Objects.equals(this.abortScaleDownDelaySeconds, v1alpha1BlueGreenStrategy.abortScaleDownDelaySeconds) &&
        Objects.equals(this.activeMetadata, v1alpha1BlueGreenStrategy.activeMetadata) &&
        Objects.equals(this.activeService, v1alpha1BlueGreenStrategy.activeService) &&
        Objects.equals(this.antiAffinity, v1alpha1BlueGreenStrategy.antiAffinity) &&
        Objects.equals(this.autoPromotionEnabled, v1alpha1BlueGreenStrategy.autoPromotionEnabled) &&
        Objects.equals(this.autoPromotionSeconds, v1alpha1BlueGreenStrategy.autoPromotionSeconds) &&
        Objects.equals(this.maxUnavailable, v1alpha1BlueGreenStrategy.maxUnavailable) &&
        Objects.equals(this.postPromotionAnalysis, v1alpha1BlueGreenStrategy.postPromotionAnalysis) &&
        Objects.equals(this.prePromotionAnalysis, v1alpha1BlueGreenStrategy.prePromotionAnalysis) &&
        Objects.equals(this.previewMetadata, v1alpha1BlueGreenStrategy.previewMetadata) &&
        Objects.equals(this.previewReplicaCount, v1alpha1BlueGreenStrategy.previewReplicaCount) &&
        Objects.equals(this.previewService, v1alpha1BlueGreenStrategy.previewService) &&
        Objects.equals(this.scaleDownDelayRevisionLimit, v1alpha1BlueGreenStrategy.scaleDownDelayRevisionLimit) &&
        Objects.equals(this.scaleDownDelaySeconds, v1alpha1BlueGreenStrategy.scaleDownDelaySeconds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(abortScaleDownDelaySeconds, activeMetadata, activeService, antiAffinity, autoPromotionEnabled, autoPromotionSeconds, maxUnavailable, postPromotionAnalysis, prePromotionAnalysis, previewMetadata, previewReplicaCount, previewService, scaleDownDelayRevisionLimit, scaleDownDelaySeconds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1BlueGreenStrategy {\n");
    sb.append("    abortScaleDownDelaySeconds: ").append(toIndentedString(abortScaleDownDelaySeconds)).append("\n");
    sb.append("    activeMetadata: ").append(toIndentedString(activeMetadata)).append("\n");
    sb.append("    activeService: ").append(toIndentedString(activeService)).append("\n");
    sb.append("    antiAffinity: ").append(toIndentedString(antiAffinity)).append("\n");
    sb.append("    autoPromotionEnabled: ").append(toIndentedString(autoPromotionEnabled)).append("\n");
    sb.append("    autoPromotionSeconds: ").append(toIndentedString(autoPromotionSeconds)).append("\n");
    sb.append("    maxUnavailable: ").append(toIndentedString(maxUnavailable)).append("\n");
    sb.append("    postPromotionAnalysis: ").append(toIndentedString(postPromotionAnalysis)).append("\n");
    sb.append("    prePromotionAnalysis: ").append(toIndentedString(prePromotionAnalysis)).append("\n");
    sb.append("    previewMetadata: ").append(toIndentedString(previewMetadata)).append("\n");
    sb.append("    previewReplicaCount: ").append(toIndentedString(previewReplicaCount)).append("\n");
    sb.append("    previewService: ").append(toIndentedString(previewService)).append("\n");
    sb.append("    scaleDownDelayRevisionLimit: ").append(toIndentedString(scaleDownDelayRevisionLimit)).append("\n");
    sb.append("    scaleDownDelaySeconds: ").append(toIndentedString(scaleDownDelaySeconds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

