/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.models.V1alpha1ScopeDetail;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha1KayentaScope
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-19T21:57:47.017Z[Etc/UTC]")
public class V1alpha1KayentaScope {
  public static final String SERIALIZED_NAME_CONTROL_SCOPE = "controlScope";
  @SerializedName(SERIALIZED_NAME_CONTROL_SCOPE)
  private V1alpha1ScopeDetail controlScope;

  public static final String SERIALIZED_NAME_EXPERIMENT_SCOPE = "experimentScope";
  @SerializedName(SERIALIZED_NAME_EXPERIMENT_SCOPE)
  private V1alpha1ScopeDetail experimentScope;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name = "";


  public V1alpha1KayentaScope controlScope(V1alpha1ScopeDetail controlScope) {
    
    this.controlScope = controlScope;
    return this;
  }

   /**
   * Get controlScope
   * @return controlScope
  **/
  @ApiModelProperty(required = true, value = "")

  public V1alpha1ScopeDetail getControlScope() {
    return controlScope;
  }


  public void setControlScope(V1alpha1ScopeDetail controlScope) {
    this.controlScope = controlScope;
  }


  public V1alpha1KayentaScope experimentScope(V1alpha1ScopeDetail experimentScope) {
    
    this.experimentScope = experimentScope;
    return this;
  }

   /**
   * Get experimentScope
   * @return experimentScope
  **/
  @ApiModelProperty(required = true, value = "")

  public V1alpha1ScopeDetail getExperimentScope() {
    return experimentScope;
  }


  public void setExperimentScope(V1alpha1ScopeDetail experimentScope) {
    this.experimentScope = experimentScope;
  }


  public V1alpha1KayentaScope name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1KayentaScope v1alpha1KayentaScope = (V1alpha1KayentaScope) o;
    return Objects.equals(this.controlScope, v1alpha1KayentaScope.controlScope) &&
        Objects.equals(this.experimentScope, v1alpha1KayentaScope.experimentScope) &&
        Objects.equals(this.name, v1alpha1KayentaScope.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(controlScope, experimentScope, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1KayentaScope {\n");
    sb.append("    controlScope: ").append(toIndentedString(controlScope)).append("\n");
    sb.append("    experimentScope: ").append(toIndentedString(experimentScope)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

